import type { MonarchModuleManifest } from '../../core';

export const deviceManifest: MonarchModuleManifest = {
  id: 'device',
  name: 'Monarch Device Control',
  version: '0.2.0',
  kind: 'domain',
  description: 'Narrow, confirmation-gated Windows desktop actions for local Monarch tasks.',
  owns: ['device control', 'windows desktop', 'recycle bin', 'active browser', 'управление компьютером', 'корзина', 'браузер'],
  permissions: ['read', 'delete', 'device-control'],
  events: [
    'device.activated',
    'device.app.opened',
    'device.browser.opened',
    'device.brightness.read',
    'device.brightness.changed',
    'device.recycle_bin.emptied',
    'device.browser.closed',
  ],
  capabilities: [
    {
      id: 'device.brightness.get',
      moduleId: 'device',
      title: 'Read active display brightness',
      description: 'Read the current WMI brightness of the active built-in Windows display.',
      risk: 'read',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
      routing: {
        aliases: ['read brightness', 'current brightness', 'какая яркость'],
        keywords: ['brightness', 'display', 'яркость', 'экран'],
        examples: ['какая сейчас яркость экрана'],
        intentKinds: ['device-control'],
      },
    },
    {
      id: 'device.brightness.set',
      moduleId: 'device',
      title: 'Set active display brightness',
      description: 'Set or adjust the WMI brightness of the active built-in Windows display and verify it by rereading the device.',
      risk: 'device-control',
      inputSchema: {
        type: 'object',
        properties: {
          operation: { type: 'string', enum: ['set', 'change'] },
          value: { type: 'integer', minimum: 0, maximum: 100 },
          delta: { type: 'integer', minimum: -100, maximum: 100 },
        },
        required: ['operation'],
        additionalProperties: false,
      },
      routing: {
        aliases: ['set brightness', 'change brightness', 'установи яркость'],
        keywords: ['brightness', 'display', 'яркость', 'экран'],
        examples: ['установи яркость на 50 процентов'],
        intentKinds: ['device-control'],
      },
    },
    {
      id: 'device.app.open',
      moduleId: 'device',
      title: 'Open an installed Windows application',
      description: 'Resolve an allowlisted alias or an installed Start app and launch it after one-time confirmation.',
      risk: 'device-control',
      inputSchema: {
        type: 'object',
        properties: {
          app: { type: 'string', minLength: 1, maxLength: 120 },
        },
        required: ['app'],
        additionalProperties: false,
      },
      routing: {
        aliases: ['open app', 'launch program', 'открой приложение', 'запусти программу'],
        keywords: ['open', 'launch', 'app', 'program', 'открой', 'запусти', 'приложение'],
        examples: ['открой калькулятор'],
        intentKinds: ['device-control'],
      },
    },
    {
      id: 'device.browser.open',
      moduleId: 'device',
      title: 'Open a safe web target in a browser',
      description: 'Open an HTTP(S) URL or an encoded search query in the default or explicitly selected browser.',
      risk: 'device-control',
      inputSchema: {
        type: 'object',
        properties: {
          url: { type: 'string', minLength: 1, maxLength: 2048 },
          query: { type: 'string', minLength: 1, maxLength: 500 },
          browser: { type: 'string', enum: ['default', 'chrome', 'edge', 'firefox'] },
          provider: { type: 'string', enum: ['google', 'youtube'] },
        },
        additionalProperties: false,
      },
      routing: {
        aliases: ['open website', 'browse to', 'открой сайт', 'открой в браузере'],
        keywords: ['browser', 'website', 'url', 'браузер', 'сайт', 'ссылка'],
        examples: ['открой сайт example.com в браузере'],
        intentKinds: ['device-control'],
      },
    },
    {
      id: 'device.recycle-bin.empty',
      moduleId: 'device',
      title: 'Empty Windows Recycle Bin',
      description: 'Empty the current Windows user recycle bin after one-time confirmation.',
      risk: 'delete',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
      routing: {
        aliases: ['empty recycle bin', 'clear recycle bin', 'очисти корзину'],
        keywords: ['empty', 'clear', 'recycle bin', 'очисти', 'корзина'],
        examples: ['очисти корзину на компьютере'],
        intentKinds: ['device-control'],
      },
    },
    {
      id: 'device.browser.close-active',
      moduleId: 'device',
      title: 'Close active browser',
      description: 'Gracefully close the foreground window only when it belongs to a known browser.',
      risk: 'device-control',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
      routing: {
        aliases: ['close active browser', 'закрой активный браузер'],
        keywords: ['close', 'active browser', 'закрой', 'активный браузер'],
        examples: ['закрой активный браузер'],
        intentKinds: ['device-control'],
      },
    },
    {
      id: 'device.desktop.actions',
      moduleId: 'device',
      title: 'Run combined desktop actions',
      description: 'Run a bounded set of supported Windows desktop actions under one confirmation.',
      risk: 'device-control',
      inputSchema: {
        type: 'object',
        properties: {
          emptyRecycleBin: { type: 'boolean' },
          closeActiveBrowser: { type: 'boolean' },
        },
        additionalProperties: false,
      },
      routing: {
        aliases: ['desktop actions', 'действия на компьютере'],
        keywords: ['desktop', 'computer', 'компьютер', 'ноутбук'],
        examples: ['очисти корзину и закрой активный браузер'],
        intentKinds: ['device-control'],
      },
    },
  ],
};
