import { describe, it, expect } from 'vitest';
import { rm } from 'node:fs/promises';
import { createMonarchRuntime } from '../../src/bootstrap';

describe('Artifacts Module', () => {
  it('should write and list artifacts safely', async () => {
    const runtime = createMonarchRuntime({
      enabledModules: ['artifacts'],
      enableLocalSystemRouter: false,
    });
    let artifactPath = '';

    await runtime.kernel.start();
    try {
      const written = await runtime.kernel.execute({
        id: 'exec_smoke_artifact_write',
        intentId: 'intent_smoke_artifact_write',
        moduleId: 'artifacts',
        capabilityId: 'artifacts.write',
        input: {
          type: 'md',
          fileName: `smoke-artifact-${Date.now()}`,
          content: '# Smoke Artifact\n\nGenerated by smoke.',
        },
        createdAt: new Date(0).toISOString(),
        requestedBy: 'smoke',
        confirmed: true,
      });
      artifactPath = String((written.output as { path?: unknown } | undefined)?.path || '');
      
      if (!written.ok) throw new Error(written.summary);
      expect(written.ok).toBe(true);
      expect(artifactPath.endsWith('.md')).toBe(true);

      const listed = await runtime.kernel.execute({
        id: 'exec_smoke_artifact_list',
        intentId: 'intent_smoke_artifact_list',
        moduleId: 'artifacts',
        capabilityId: 'artifacts.list',
        input: { limit: 50 },
        createdAt: new Date(0).toISOString(),
        requestedBy: 'smoke',
      });
      
      const files = (listed.output as { files?: Array<{ path?: unknown }> } | undefined)?.files || [];
      if (!listed.ok) throw new Error(listed.summary);
      expect(listed.ok).toBe(true);
      expect(files.some((file) => file.path === artifactPath)).toBe(true);
    } finally {
      await runtime.kernel.stop().catch(() => undefined);
      if (artifactPath) {
        await rm(artifactPath, { force: true });
      }
    }
  });
});
