import type { MonarchModuleManifest } from '../../core';

export const astraManifest: MonarchModuleManifest = {
  id: 'astra',
  name: 'Monarch Skills',
  version: '0.1.0',
  kind: 'system',
  description: 'Monolithic local skill layer for Oscar-facing capability cards, slot previews, and Monarch skill indexing.',
  owns: [
    'astra',
    'skills',
    'agent cards',
    'slots',
    'oscar integration',
    'навыки',
    'карточки навыков',
    'слоты',
    'интеграция oscar',
  ],
  permissions: ['read'],
  events: [
    'astra.activated',
    'astra.skill_index.created',
    'astra.slot.previewed',
  ],
  capabilities: [
    {
      id: 'astra.skills.index',
      moduleId: 'astra',
      title: 'Index Oscar skills',
      description: 'Return compact Oscar-facing agent cards for active Monarch capabilities.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {
          includeSystem: { type: 'boolean' },
        },
        additionalProperties: false,
      },
      routing: {
        aliases: [
          'astra skills',
          'skill index',
          'agent cards',
          'покажи навыки astra',
          'карта навыков',
          'карточки навыков',
        ],
        keywords: [
          'astra',
          'skills',
          'skill',
          'agent',
          'cards',
          'capabilities',
          'навыки',
          'карточки',
          'возможности',
          'способности',
        ],
        examples: [
          'show Astra skill index',
          'покажи карту навыков для Oscar',
        ],
        intentKinds: ['astra.read', 'skills.index', 'agent.cards'],
      },
    },
    {
      id: 'astra.skill.explain',
      moduleId: 'astra',
      title: 'Explain skill card',
      description: 'Return one Oscar-facing agent card for a selected Monarch capability.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {
          capabilityId: { type: 'string' },
        },
        required: ['capabilityId'],
        additionalProperties: false,
      },
      routing: {
        aliases: [
          'explain skill',
          'explain capability',
          'объясни навык',
          'объясни capability',
          'карточка навыка',
        ],
        keywords: [
          'astra',
          'skill',
          'capability',
          'explain',
          'card',
          'навык',
          'возможность',
          'объясни',
          'карточка',
        ],
        examples: [
          'explain skill memory.search',
          'объясни навык security.scan.system',
        ],
        intentKinds: ['astra.read', 'skill.explain', 'capability.explain'],
      },
    },
    {
      id: 'astra.slot.preview',
      moduleId: 'astra',
      title: 'Preview skill slot',
      description: 'Build a read-only preview of the runtime slot Oscar would receive for a capability.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {
          capabilityId: { type: 'string' },
          intentText: { type: 'string' },
        },
        required: ['capabilityId'],
        additionalProperties: false,
      },
      routing: {
        aliases: [
          'preview slot',
          'skill slot',
          'покажи слот',
          'слот навыка',
          'preview astra slot',
        ],
        keywords: [
          'astra',
          'slot',
          'slots',
          'runtime',
          'context',
          'слот',
          'слоты',
          'контекст',
        ],
        examples: [
          'preview slot for memory.search',
          'покажи слот для workspace.files.read',
        ],
        intentKinds: ['astra.read', 'slot.preview'],
      },
    },
    {
      id: 'astra.oscar.bridge.describe',
      moduleId: 'astra',
      title: 'Describe Oscar bridge',
      description: 'Describe the planned local integration contract between Oscar and the monolithic Astra layer.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {},
        additionalProperties: false,
      },
      routing: {
        aliases: [
          'oscar bridge',
          'astra oscar integration',
          'интеграция oscar',
          'мост oscar',
          'связь astra oscar',
        ],
        keywords: [
          'astra',
          'oscar',
          'bridge',
          'integration',
          'api',
          'интеграция',
          'мост',
          'связь',
        ],
        examples: [
          'describe Astra Oscar integration',
          'покажи план интеграции Oscar с Astra',
        ],
        intentKinds: ['astra.read', 'oscar.bridge'],
      },
    },
    {
      id: 'astra.agent-skills.list',
      moduleId: 'astra',
      title: 'List Agent Skills',
      description: 'Discover Codex-, Claude Code-, and Monarch-compatible SKILL.md workflows without loading their bodies.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {
          refresh: { type: 'boolean' },
        },
        additionalProperties: false,
      },
      routing: {
        aliases: ['agent skills', 'Codex skills', 'Claude skills', 'система навыков', 'навыки SKILL.md'],
        keywords: ['agent', 'skills', 'SKILL.md', 'Codex', 'Claude', 'навыки'],
        examples: ['покажи Agent Skills', 'list Codex and Claude skills'],
        intentKinds: ['skills.list', 'agent-skills.list'],
      },
    },
    {
      id: 'astra.agent-skills.match',
      moduleId: 'astra',
      title: 'Match Agent Skills',
      description: 'Rank skills for a prompt using deterministic explicit and implicit invocation rules.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {
          query: { type: 'string' },
          limit: { type: 'number' },
        },
        required: ['query'],
        additionalProperties: false,
      },
      routing: {
        aliases: ['match skill', 'skill radar', 'suggest skill', 'радар навыков', 'подбери навык'],
        keywords: ['match', 'radar', 'skill', 'recommend', 'радар', 'навык'],
        examples: ['подбери навык для генерации изображения', 'skill radar for this task'],
        intentKinds: ['skills.match', 'agent-skills.match'],
      },
    },
    {
      id: 'astra.agent-skills.activate',
      moduleId: 'astra',
      title: 'Activate Agent Skill',
      description: 'Load one selected SKILL.md body and render invocation arguments without bypassing Monarch permissions.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {
          skill: { type: 'string' },
          prompt: { type: 'string' },
        },
        required: ['skill'],
        additionalProperties: false,
      },
      routing: {
        aliases: ['activate skill', 'use skill', 'загрузи навык', 'активируй навык'],
        keywords: ['activate', 'invoke', 'skill', 'активируй', 'навык'],
        examples: ['активируй навык imagegen', 'activate skill playwright'],
        intentKinds: ['skills.activate', 'agent-skills.activate'],
      },
    },
  ],
};
