import type {
  MonarchActionPredicate,
  MonarchAgentCapabilityMetadataInput,
  MonarchAgentCapabilityReconciliationDescriptor,
  MonarchModuleManifest,
} from '../../core';

interface WorkspaceFileAgentOptions {
  tags: string[];
  effectKind: string;
  effectDescription: string;
  idempotency: 'idempotent' | 'conditional' | 'non-idempotent';
  reversibility: 'automatic' | 'manual' | 'irreversible';
  destructive?: boolean;
  verificationKind?: 'predicate' | 'read-after-write' | 'schema' | 'runtime-status' | 'external-receipt';
  verificationPredicate?: MonarchActionPredicate;
  verificationDescription: string;
  reconciliation?: MonarchAgentCapabilityReconciliationDescriptor;
}

function workspaceFileAgent(options: WorkspaceFileAgentOptions): MonarchAgentCapabilityMetadataInput {
  const verificationKind = options.verificationKind || 'external-receipt';
  const verificationPredicate = options.verificationPredicate
    || (verificationKind === 'external-receipt' || verificationKind === 'runtime-status'
      ? { kind: 'status' as const, target: 'result.output.verified', value: true }
      : undefined);
  return {
    tags: ['workspace', 'filesystem', ...options.tags],
    preconditions: [{
      kind: 'canonical-path-policy',
      description: 'The exact canonical input path must remain inside an explicitly allowed root and outside production Safe.',
    }],
    effects: [{
      kind: options.effectKind,
      description: options.effectDescription,
      targetScope: 'workspace',
    }],
    idempotency: options.idempotency,
    reversibility: options.reversibility,
    effectProfile: {
      mutation: 'persistent',
      targetScope: 'workspace',
      reversibility: options.reversibility,
      privilege: 'normal',
      dataSensitivity: 'private',
      communication: 'none',
      financialImpact: false,
      identityImpact: false,
      securityImpact: options.destructive === true,
    },
    supportedSources: options.destructive
      ? ['desktop', 'system', 'smoke']
      : ['desktop', 'voice', 'telegram', 'api', 'system', 'smoke'],
    estimatedLatency: 'short',
    computeClass: 'light',
    cancellation: 'supported',
    verification: [{
      kind: verificationKind,
      description: options.verificationDescription,
      required: true,
      ...(verificationPredicate ? { predicate: verificationPredicate } : {}),
    }],
    ...(options.reconciliation ? { reconciliation: options.reconciliation } : {}),
  };
}

export const workspaceManifest: MonarchModuleManifest = {
  id: 'workspace',
  name: 'Monarch Workspace',
  version: '0.1.0',
  kind: 'tooling',
  description: 'Sandboxed workspace file operations adapted from MARK-ALFA file tooling.',
  owns: ['workspace', 'files', 'project files', 'filesystem'],
  permissions: ['read', 'write', 'delete'],
  events: [
    'workspace.activated',
    'workspace.file.written',
    'workspace.file.replaced',
    'workspace.file.deleted',
    'workspace.directory.created',
    'workspace.path.copied',
    'workspace.path.moved',
    'workspace.path.trashed',
  ],
  capabilities: [
    {
      id: 'workspace.root.get',
      moduleId: 'workspace',
      title: 'Get workspace root',
      description: 'Return the exact authoritative filesystem path of the active Monarch workspace.',
      risk: 'read',
      agent: {
        tags: ['workspace', 'filesystem', 'discovery', 'read'],
        effects: [{
          kind: 'workspace-root-observation',
          description: 'Returns the configured workspace root without reading file contents.',
          targetScope: 'workspace',
        }],
        idempotency: 'idempotent',
        reversibility: 'automatic',
        effectProfile: {
          mutation: 'none',
          targetScope: 'workspace',
          reversibility: 'automatic',
          privilege: 'normal',
          dataSensitivity: 'private',
          communication: 'none',
          financialImpact: false,
          identityImpact: false,
          securityImpact: false,
        },
        supportedSources: ['desktop', 'voice', 'telegram', 'api', 'system', 'smoke'],
        estimatedLatency: 'instant',
        computeClass: 'light',
        cancellation: 'unsupported',
        verification: [{
          kind: 'schema',
          description: 'The result must contain the authoritative workspace root.',
        }],
        examples: [{ goal: 'Locate the active project root before reading files.' }],
      },
      routing: {
        aliases: ['workspace root', 'workspace path', 'путь рабочего пространства', 'где находится рабочее пространство'],
        keywords: ['workspace', 'root', 'path', 'location', 'рабочее пространство', 'путь', 'расположение'],
        examples: ['where is the workspace', 'укажи точный путь рабочего пространства'],
        intentKinds: ['workspace.info', 'file.operation'],
      },
      inputSchema: {
        type: 'object',
        properties: {},
        additionalProperties: false,
      },
    },
    {
      id: 'workspace.storage.audit',
      moduleId: 'workspace',
      title: 'Audit local storage',
      description: 'Read a bounded local directory tree and return deterministic size/count observations without following reparse points.',
      risk: 'read',
      agent: {
        tags: ['workspace', 'filesystem', 'storage', 'audit', 'disk', 'read', 'observation'],
        preconditions: [{
          kind: 'canonical-path-policy',
          description: 'Every traversed path must stay inside the exact approved root and outside Monarch Safe and filesystem red zones.',
        }],
        effects: [{
          kind: 'storage-audit-observation',
          description: 'Observes logical sizes, entry counts, empty directories, skips, timestamps, and project markers without mutation.',
          targetScope: 'device',
        }],
        idempotency: 'idempotent',
        reversibility: 'automatic',
        effectProfile: {
          mutation: 'none',
          targetScope: 'device',
          reversibility: 'automatic',
          privilege: 'normal',
          dataSensitivity: 'private',
          communication: 'none',
          financialImpact: false,
          identityImpact: false,
          securityImpact: false,
        },
        supportedSources: ['desktop', 'system'],
        estimatedLatency: 'long',
        computeClass: 'medium',
        cancellation: 'supported',
        verification: [{
          kind: 'external-receipt',
          description: 'The worker observation must be bounded, policy-filtered, and marked verified by the capability.',
          required: true,
          predicate: { kind: 'status', target: 'result.output.observationVerified', value: true },
        }],
        examples: [
          { root: 'D:\\', topN: 20, maxDepth: 64, maxEntries: 500000, maxWallTimeMs: 120000 },
          { goal: 'Проведи аудит папок на диске D и покажи самые большие каталоги.' },
        ],
      },
      routing: {
        aliases: ['storage audit', 'disk audit', 'folder audit', 'аудит диска', 'аудит папок', 'сканирование диска'],
        keywords: ['audit', 'scan', 'storage', 'disk', 'folders', 'sizes', 'аудит', 'скан', 'диск', 'папки', 'размеры'],
        examples: ['проведи аудит папок на диске D', 'scan D drive folders and report sizes'],
        intentKinds: ['file.operation', 'workspace.info'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          root: { type: 'string' },
          topN: { type: 'integer', minimum: 1, maximum: 100 },
          maxDepth: { type: 'integer', minimum: 0, maximum: 256 },
          maxEntries: { type: 'integer', minimum: 1, maximum: 2000000 },
          maxWallTimeMs: { type: 'integer', minimum: 100, maximum: 600000 },
        },
        required: ['root'],
        additionalProperties: false,
      },
    },
    {
      id: 'workspace.files.read',
      moduleId: 'workspace',
      title: 'Read file',
      description: 'Read a text file inside the allowed workspace roots.',
      risk: 'read',
      agent: {
        tags: ['workspace', 'filesystem', 'file', 'read'],
        preconditions: [{
          kind: 'workspace-confined-path',
          description: 'The requested path must resolve inside an allowed workspace root.',
        }],
        effects: [{
          kind: 'file-content-observation',
          description: 'Returns bounded text content without changing the file.',
          targetScope: 'workspace',
        }],
        idempotency: 'idempotent',
        reversibility: 'automatic',
        effectProfile: {
          mutation: 'none',
          targetScope: 'workspace',
          reversibility: 'automatic',
          privilege: 'normal',
          dataSensitivity: 'private',
          communication: 'none',
          financialImpact: false,
          identityImpact: false,
          securityImpact: false,
        },
        supportedSources: ['desktop', 'voice', 'telegram', 'api', 'system', 'smoke'],
        estimatedLatency: 'short',
        computeClass: 'light',
        cancellation: 'unsupported',
        verification: [{
          kind: 'schema',
          description: 'The observation must identify the resolved path and bounded file content.',
        }],
        examples: [{ path: 'package.json', purpose: 'Inspect project metadata.' }],
      },
      routing: {
        aliases: ['read file', 'show file', 'open file', 'прочитай файл', 'прочитать файл', 'открой файл', 'открыть файл', 'покажи файл'],
        keywords: ['read', 'show', 'open', 'file', 'workspace', 'прочитай', 'прочитать', 'открой', 'открыть', 'покажи', 'показать', 'файл', 'файла', 'путь'],
        examples: ['read file package.json', 'прочитай package.json', 'можешь прочитать package.json'],
        intentKinds: ['file.read', 'file.operation'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          path: { type: 'string' },
          maxBytes: { type: 'number' },
        },
        required: ['path'],
        additionalProperties: false,
      },
    },
    {
      id: 'workspace.files.list',
      moduleId: 'workspace',
      title: 'List files',
      description: 'List files and directories inside an allowed workspace root.',
      risk: 'read',
      agent: {
        tags: ['workspace', 'filesystem', 'directory', 'list', 'read'],
        preconditions: [{
          kind: 'workspace-confined-path',
          description: 'The requested directory must resolve inside an allowed workspace root.',
        }],
        effects: [{
          kind: 'directory-listing-observation',
          description: 'Returns a bounded directory listing without changing the workspace.',
          targetScope: 'workspace',
        }],
        idempotency: 'idempotent',
        reversibility: 'automatic',
        effectProfile: {
          mutation: 'none',
          targetScope: 'workspace',
          reversibility: 'automatic',
          privilege: 'normal',
          dataSensitivity: 'private',
          communication: 'none',
          financialImpact: false,
          identityImpact: false,
          securityImpact: false,
        },
        supportedSources: ['desktop', 'voice', 'telegram', 'api', 'system', 'smoke'],
        estimatedLatency: 'short',
        computeClass: 'light',
        cancellation: 'unsupported',
        verification: [{
          kind: 'schema',
          description: 'The observation must contain a bounded list of workspace entries.',
        }],
        examples: [{ path: 'src', purpose: 'Discover implementation files.' }],
      },
      routing: {
        aliases: ['list files', 'show files', 'workspace files', 'покажи файлы', 'список файлов', 'просмотри папки', 'перечисли папки'],
        keywords: ['list', 'show', 'view', 'files', 'folder', 'directory', 'workspace', 'покажи', 'просмотри', 'посмотри', 'перечисли', 'список', 'файлы', 'папка', 'директория'],
        examples: ['list files in src', 'покажи файлы в src', 'просмотри названия папок в корневой папке'],
        intentKinds: ['file.list', 'file.operation'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          path: { type: 'string' },
          recursive: { type: 'boolean' },
          limit: { type: 'number' },
          entryType: { type: 'string' },
          extension: { type: 'string' },
        },
        additionalProperties: false,
      },
    },
    {
      id: 'workspace.files.search',
      moduleId: 'workspace',
      title: 'Search files',
      description: 'Search text files inside an allowed workspace root.',
      risk: 'read',
      agent: {
        tags: ['workspace', 'filesystem', 'search', 'read'],
        preconditions: [{
          kind: 'workspace-confined-path',
          description: 'The search root must resolve inside an allowed workspace root.',
        }],
        effects: [{
          kind: 'file-search-observation',
          description: 'Returns bounded matches without changing searched files.',
          targetScope: 'workspace',
        }],
        idempotency: 'idempotent',
        reversibility: 'automatic',
        effectProfile: {
          mutation: 'none',
          targetScope: 'workspace',
          reversibility: 'automatic',
          privilege: 'normal',
          dataSensitivity: 'private',
          communication: 'none',
          financialImpact: false,
          identityImpact: false,
          securityImpact: false,
        },
        supportedSources: ['desktop', 'voice', 'telegram', 'api', 'system', 'smoke'],
        estimatedLatency: 'short',
        computeClass: 'medium',
        cancellation: 'unsupported',
        verification: [{
          kind: 'schema',
          description: 'The observation must contain bounded search matches and their paths.',
        }],
        examples: [{ query: 'submitIntentJob', path: 'src', purpose: 'Find a live call path.' }],
      },
      routing: {
        aliases: ['search files', 'find in files', 'grep files', 'найди в файлах', 'поиск по файлам'],
        keywords: ['search', 'find', 'grep', 'files', 'workspace', 'найди', 'ищи', 'поиск', 'файлах', 'файлы'],
        examples: ['search files for router', 'найди в файлах AssistantModule'],
        intentKinds: ['file.search', 'file.operation'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          query: { type: 'string' },
          path: { type: 'string' },
          limit: { type: 'number' },
        },
        required: ['query'],
        additionalProperties: false,
      },
    },
    {
      id: 'workspace.files.write',
      moduleId: 'workspace',
      title: 'Write file',
      description: 'Write a text file inside the allowed workspace roots.',
      risk: 'write',
      agent: {
        tags: ['workspace', 'filesystem', 'file', 'write', 'mutation'],
        preconditions: [{
          kind: 'workspace-confined-path',
          description: 'The target path must resolve inside an allowed workspace root.',
        }],
        effects: [{
          kind: 'file-write',
          description: 'Creates or replaces bounded text content at a workspace-confined path.',
          targetScope: 'workspace',
        }],
        idempotency: 'conditional',
        reversibility: 'manual',
        effectProfile: {
          mutation: 'persistent',
          targetScope: 'workspace',
          reversibility: 'manual',
          privilege: 'normal',
          dataSensitivity: 'private',
          communication: 'none',
          financialImpact: false,
          identityImpact: false,
          securityImpact: false,
        },
        supportedSources: ['desktop', 'voice', 'telegram', 'api', 'system', 'smoke'],
        estimatedLatency: 'short',
        computeClass: 'light',
        cancellation: 'supported',
        verification: [{
          kind: 'read-after-write',
          description: 'A deterministic read must confirm the target exists with the expected content.',
          required: true,
        }],
        reconciliation: {
          capabilityId: 'workspace.files.read',
          inputBindings: { path: 'path' },
          constantInput: { maxBytes: 524288 },
          targetInputKey: 'path',
          observationTargetPath: 'path',
          assertion: {
            kind: 'equals-source-input',
            observationPath: 'content',
            sourceInputKey: 'content',
          },
        },
        examples: [{ path: 'runtime/report.md', purpose: 'Persist a generated workspace report.' }],
      },
      routing: {
        aliases: ['write file', 'create file', 'save file', 'создай файл', 'запиши файл', 'сохрани файл'],
        keywords: ['write', 'create', 'save', 'file', 'workspace', 'создай', 'запиши', 'сохрани', 'файл'],
        examples: ['write file runtime/example.txt', 'создай файл runtime/example.txt'],
        intentKinds: ['file.write', 'file.generation'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          path: { type: 'string' },
          content: { type: 'string' },
          overwrite: { type: 'boolean' },
        },
        required: ['path', 'content'],
        additionalProperties: false,
      },
    },
    {
      id: 'workspace.files.inspect-batch',
      moduleId: 'workspace',
      title: 'Inspect files in deterministic pages',
      description: 'Enumerate a filesystem target, read supported UTF-8 documents, hash every inspected file, report binary metadata and explicit skips, and continue with a freshness-bound cursor.',
      risk: 'read',
      agent: {
        tags: ['workspace', 'filesystem', 'file', 'read', 'batch', 'pagination', 'digest', 'desktop', 'documents'],
        preconditions: [{
          kind: 'workspace-confined-path',
          description: 'The exact path or known folder must remain inside an allowed root and outside every red zone, including Monarch Safe.',
        }],
        effects: [{
          kind: 'file-batch-observation',
          description: 'Returns one deterministic page with text, metadata, digests, skips, and a continuation cursor.',
          targetScope: 'workspace',
        }],
        idempotency: 'idempotent',
        reversibility: 'automatic',
        effectProfile: {
          mutation: 'none',
          targetScope: 'workspace',
          reversibility: 'automatic',
          privilege: 'normal',
          dataSensitivity: 'private',
          communication: 'none',
          financialImpact: false,
          identityImpact: false,
          securityImpact: false,
        },
        supportedSources: ['desktop', 'coder', 'voice', 'telegram', 'api', 'system', 'smoke'],
        estimatedLatency: 'long',
        computeClass: 'medium',
        cancellation: 'supported',
        verification: [{
          kind: 'schema',
          description: 'The page must bind to an exact root and snapshot, and expose coverage plus a freshness-bound continuation cursor.',
          required: true,
        }],
        examples: [{ knownFolder: 'desktop', purpose: 'Summarize every supported Desktop document.' }],
      },
      routing: {
        aliases: ['inspect files in batches', 'summarize all desktop files', 'перескажи все файлы', 'прочитай все документы'],
        keywords: ['inspect', 'batch', 'pagination', 'digest', 'summarize', 'desktop', 'documents', 'перескажи', 'файлы', 'рабочий стол', 'документы'],
        examples: ['Перескажи все мои файлы на рабочем столе', 'inspect every document in this folder'],
        intentKinds: ['file.read', 'file.list', 'file.operation'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          path: { type: 'string' },
          knownFolder: { type: 'string', enum: ['desktop', 'downloads'] },
          cursor: { type: 'string', maxLength: 4096 },
          recursive: { type: 'boolean' },
          pageSize: { type: 'integer', minimum: 1, maximum: 50 },
          maxBytesPerFile: { type: 'integer', minimum: 1, maximum: 262144 },
          maxTotalContentBytes: { type: 'integer', minimum: 1, maximum: 524288 },
          maxEntries: { type: 'integer', minimum: 1, maximum: 100000 },
        },
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          schemaVersion: { type: 'string' },
          root: { type: 'string' },
          snapshotId: { type: 'string' },
          items: { type: 'array' },
          skips: { type: 'array' },
          coverage: { type: 'object' },
          nextCursor: { anyOf: [{ type: 'string' }, { type: 'null' }] },
          complete: { type: 'boolean' },
        },
        required: ['schemaVersion', 'root', 'snapshotId', 'items', 'skips', 'coverage', 'nextCursor', 'complete'],
        additionalProperties: false,
      },
    },
    {
      id: 'workspace.known-folder.resolve',
      moduleId: 'workspace',
      title: 'Resolve a Windows known folder',
      description: 'Resolve Desktop or Downloads to the exact current path and verify the filesystem policy before later inspection.',
      risk: 'read',
      agent: {
        tags: ['workspace', 'known-folder', 'desktop', 'downloads', 'resolve', 'read'],
        effects: [{
          kind: 'known-folder-observation',
          description: 'Returns the exact Kernel-resolved known-folder path and existence state.',
          targetScope: 'workspace',
        }],
        idempotency: 'idempotent',
        reversibility: 'automatic',
        effectProfile: {
          mutation: 'none',
          targetScope: 'workspace',
          reversibility: 'automatic',
          privilege: 'normal',
          dataSensitivity: 'private',
          communication: 'none',
          financialImpact: false,
          identityImpact: false,
          securityImpact: false,
        },
        supportedSources: ['desktop', 'coder', 'voice', 'telegram', 'api', 'system', 'smoke'],
        estimatedLatency: 'instant',
        computeClass: 'light',
        cancellation: 'supported',
        verification: [{ kind: 'schema', description: 'The result contains the exact resolved path and existence state.' }],
      },
      routing: {
        aliases: ['resolve desktop', 'resolve downloads', 'найди рабочий стол', 'путь загрузок'],
        keywords: ['resolve', 'known folder', 'desktop', 'downloads', 'рабочий стол', 'загрузки', 'путь'],
        examples: ['resolve the Desktop folder'],
        intentKinds: ['file.read', 'file.list', 'file.operation'],
      },
      inputSchema: {
        type: 'object',
        properties: { knownFolder: { type: 'string', enum: ['desktop', 'downloads'] } },
        required: ['knownFolder'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          knownFolder: { type: 'string' },
          path: { type: 'string' },
          exists: { type: 'boolean' },
          directory: { type: 'boolean' },
        },
        required: ['knownFolder', 'path', 'exists', 'directory'],
        additionalProperties: false,
      },
    },
    {
      id: 'workspace.known-folder.write',
      moduleId: 'workspace',
      title: 'Write file in a known user folder',
      description: 'Write one text file directly inside Desktop or Downloads without accepting an arbitrary filesystem path.',
      risk: 'write',
      agent: {
        tags: [
          'workspace',
          'filesystem',
          'known-folder',
          'desktop',
          'downloads',
          'file',
          'write',
          'mutation',
        ],
        preconditions: [{
          kind: 'known-folder-leaf-policy',
          description: 'Kernel must resolve Desktop or Downloads and basename must be exactly one safe leaf name.',
        }],
        effects: [{
          kind: 'known-folder-file-write',
          description: 'Creates or replaces one bounded text file at the exact Kernel-resolved known-folder target.',
          targetScope: 'application',
        }],
        idempotency: 'conditional',
        reversibility: 'manual',
        effectProfile: {
          mutation: 'persistent',
          targetScope: 'application',
          reversibility: 'manual',
          privilege: 'normal',
          dataSensitivity: 'private',
          communication: 'none',
          financialImpact: false,
          identityImpact: false,
          securityImpact: false,
        },
        supportedSources: ['desktop', 'voice', 'smoke'],
        estimatedLatency: 'short',
        computeClass: 'light',
        cancellation: 'supported',
        verification: [{
          kind: 'predicate',
          description: 'Byte-for-byte readback must verify the exact resolved Desktop or Downloads target.',
          required: true,
          predicate: { kind: 'status', target: 'result.output.verified', value: true },
        }],
        examples: [{
          goal: 'Создай на рабочем столе текстовый файл с именем ромашка.',
          input: { knownFolder: 'desktop', basename: 'ромашка.txt', content: '' },
        }],
      },
      routing: {
        aliases: [
          'write file on desktop',
          'create file in downloads',
          'создай файл на рабочем столе',
          'создай файл в загрузках',
        ],
        keywords: [
          'write',
          'create',
          'file',
          'desktop',
          'downloads',
          'создай',
          'файл',
          'рабочий стол',
          'загрузки',
        ],
        examples: [
          'create text file note on desktop',
          'создай на рабочем столе текстовый файл с именем ромашка',
        ],
        intentKinds: ['file.write', 'file.generation'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          knownFolder: { type: 'string', enum: ['desktop', 'downloads'] },
          basename: { type: 'string' },
          content: { type: 'string' },
          overwrite: { type: 'boolean', enum: [false] },
        },
        required: ['knownFolder', 'basename'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: {
          knownFolder: { type: 'string' },
          basename: { type: 'string' },
          path: { type: 'string' },
          bytes: { type: 'number' },
          verified: { type: 'boolean' },
          readbackSha256: { type: 'string' },
        },
        required: ['knownFolder', 'basename', 'path', 'bytes', 'verified', 'readbackSha256'],
        additionalProperties: true,
      },
    },
    {
      id: 'workspace.files.append',
      moduleId: 'workspace',
      title: 'Append file',
      description: 'Append bounded text to a file inside the allowed workspace roots.',
      risk: 'write',
      agent: workspaceFileAgent({
        tags: ['append', 'file', 'write'],
        effectKind: 'file-append',
        effectDescription: 'Appends the supplied bytes to one exact canonical file path.',
        idempotency: 'non-idempotent',
        reversibility: 'manual',
        verificationDescription: 'Byte-for-byte readback must confirm the appended suffix at the exact target.',
        reconciliation: {
          capabilityId: 'workspace.files.read',
          inputBindings: { path: 'path' },
          constantInput: { maxBytes: 524288 },
          requiresPreActionBaseline: true,
          targetInputKey: 'path',
          observationTargetPath: 'path',
          assertion: {
            kind: 'equals-baseline-plus-source-input',
            observationPath: 'content',
            sourceInputKey: 'content',
          },
        },
      }),
      routing: {
        aliases: ['append file', 'допиши файл', 'добавь в файл'],
        keywords: ['append', 'add', 'file', 'допиши', 'добавь', 'файл'],
        examples: ['допиши файл runtime/log.txt с текстом готово'],
        intentKinds: ['file.write', 'file.operation'],
      },
      inputSchema: {
        type: 'object',
        properties: { path: { type: 'string' }, content: { type: 'string' } },
        required: ['path', 'content'],
        additionalProperties: false,
      },
    },
    {
      id: 'workspace.files.mkdir',
      moduleId: 'workspace',
      title: 'Create directory',
      description: 'Create a directory tree inside the allowed workspace roots.',
      risk: 'write',
      agent: workspaceFileAgent({
        tags: ['directory', 'mkdir', 'create'],
        effectKind: 'directory-create',
        effectDescription: 'Creates one exact canonical directory tree.',
        idempotency: 'conditional',
        reversibility: 'manual',
        verificationDescription: 'A filesystem readback must confirm that the exact target is a directory.',
      }),
      routing: {
        aliases: ['create folder', 'make folder', 'mkdir', 'создай папку', 'сделай папку'],
        keywords: ['create', 'make', 'folder', 'directory', 'mkdir', 'создай', 'сделай', 'папку', 'директорию'],
        examples: ['создай папку artifacts/generated/demo', 'сделай папку artifacts/generated/demo'],
        intentKinds: ['file.write', 'file.operation'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          path: { type: 'string' },
          ensureUnique: { type: 'boolean' },
        },
        required: ['path'],
        additionalProperties: false,
      },
    },
    {
      id: 'workspace.files.copy',
      moduleId: 'workspace',
      title: 'Copy file or directory',
      description: 'Copy a bounded file tree without following symbolic links.',
      risk: 'write',
      agent: workspaceFileAgent({
        tags: ['copy', 'file', 'directory'],
        effectKind: 'path-copy',
        effectDescription: 'Copies one exact bounded source tree to one exact canonical target without following links.',
        idempotency: 'non-idempotent',
        reversibility: 'manual',
        verificationDescription: 'Every copied file must pass byte-for-byte readback at the exact target.',
      }),
      routing: {
        aliases: ['copy file', 'copy folder', 'скопируй файл', 'скопируй папку'],
        keywords: ['copy', 'duplicate', 'file', 'folder', 'скопируй', 'дублируй', 'файл', 'папку'],
        examples: ['скопируй папку "runtime/a" в "runtime/b"'],
        intentKinds: ['file.write', 'file.operation'],
      },
      inputSchema: {
        type: 'object',
        properties: { path: { type: 'string' }, targetPath: { type: 'string' } },
        required: ['path', 'targetPath'],
        additionalProperties: false,
      },
    },
    {
      id: 'workspace.files.move',
      moduleId: 'workspace',
      title: 'Move file or directory',
      description: 'Move or rename a file or directory inside the allowed workspace roots.',
      risk: 'delete',
      agent: workspaceFileAgent({
        tags: ['move', 'rename', 'file', 'directory'],
        effectKind: 'path-move',
        effectDescription: 'Moves one exact canonical source to one exact canonical target.',
        idempotency: 'non-idempotent',
        reversibility: 'manual',
        destructive: true,
        verificationDescription: 'Readback must prove the source is absent and the exact target exists.',
      }),
      routing: {
        aliases: ['move file', 'rename file', 'перемести файл', 'переименуй папку'],
        keywords: ['move', 'rename', 'file', 'folder', 'перемести', 'переименуй', 'файл', 'папку'],
        examples: ['перемести файл "runtime/a.txt" в "runtime/b.txt"'],
        intentKinds: ['file.delete', 'file.operation'],
      },
      inputSchema: {
        type: 'object',
        properties: { path: { type: 'string' }, targetPath: { type: 'string' } },
        required: ['path', 'targetPath'],
        additionalProperties: false,
      },
    },
    {
      id: 'workspace.files.replace',
      moduleId: 'workspace',
      title: 'Replace file text',
      description: 'Replace one exact text fragment inside a text file in the allowed workspace roots.',
      risk: 'write',
      agent: workspaceFileAgent({
        tags: ['replace', 'edit', 'file', 'exact'],
        effectKind: 'file-exact-replace',
        effectDescription: 'Replaces one unambiguous exact fragment in one exact canonical text file.',
        idempotency: 'non-idempotent',
        reversibility: 'manual',
        verificationDescription: 'Byte-for-byte readback must equal the computed replacement content.',
      }),
      routing: {
        aliases: ['replace in file', 'replace file text', 'замени в файле', 'заменить текст в файле'],
        keywords: ['replace', 'edit', 'file', 'workspace', 'замени', 'заменить', 'исправь', 'файл'],
        examples: ['replace in file runtime/example.txt "old" with "new"', 'замени в файле runtime/example.txt "old" на "new"'],
        intentKinds: ['file.write', 'file.operation'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          path: { type: 'string' },
          oldText: { type: 'string' },
          newText: { type: 'string' },
        },
        required: ['path', 'oldText', 'newText'],
        additionalProperties: false,
      },
    },
    {
      id: 'workspace.files.trash',
      moduleId: 'workspace',
      title: 'Move file or directory to Recycle Bin',
      description: 'Recoverable-default removal of one exact file or directory through the Windows Recycle Bin.',
      risk: 'delete',
      agent: workspaceFileAgent({
        tags: ['trash', 'recycle', 'remove', 'file', 'directory'],
        effectKind: 'path-recycle',
        effectDescription: 'Moves one exact canonical file or directory into the current Windows user Recycle Bin.',
        idempotency: 'non-idempotent',
        reversibility: 'manual',
        destructive: true,
        verificationKind: 'external-receipt',
        verificationDescription: 'The Windows recycle operation must succeed and readback must prove the exact original target is absent.',
      }),
      routing: {
        aliases: ['trash file', 'remove file', 'delete file', 'удали файл', 'убери в корзину'],
        keywords: ['trash', 'recycle', 'delete', 'remove', 'file', 'folder', 'удали', 'корзину', 'файл', 'папку'],
        examples: ['move runtime/example.txt to recycle bin', 'удали файл runtime/example.txt'],
        intentKinds: ['file.delete', 'file.operation'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          path: { type: 'string' },
        },
        required: ['path'],
        additionalProperties: false,
      },
    },
    {
      id: 'workspace.files.delete',
      moduleId: 'workspace',
      title: 'Permanently delete file',
      description: 'Irreversibly delete one exact file only when the user explicitly requests permanent removal.',
      risk: 'delete',
      agent: workspaceFileAgent({
        tags: ['permanent', 'delete', 'irreversible', 'file'],
        effectKind: 'file-permanent-delete',
        effectDescription: 'Permanently deletes one exact canonical file without using the Recycle Bin.',
        idempotency: 'non-idempotent',
        reversibility: 'irreversible',
        destructive: true,
        verificationDescription: 'Readback must prove the exact file no longer exists.',
      }),
      routing: {
        aliases: ['permanently delete file', 'безвозвратно удали файл', 'удали файл навсегда'],
        keywords: ['permanent', 'irreversible', 'delete', 'безвозвратно', 'навсегда', 'удали'],
        examples: ['permanently delete file runtime/example.txt', 'безвозвратно удали файл runtime/example.txt'],
        intentKinds: ['file.delete', 'file.operation'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          path: { type: 'string' },
        },
        required: ['path'],
        additionalProperties: false,
      },
    },
  ],
};
