import type { MonarchModuleManifest } from '../../core';

export const workspaceManifest: MonarchModuleManifest = {
  id: 'workspace',
  name: 'Monarch Workspace',
  version: '0.1.0',
  kind: 'tooling',
  description: 'Sandboxed workspace file operations adapted from MARK-ALFA file tooling.',
  owns: ['workspace', 'files', 'project files', 'filesystem'],
  permissions: ['read', 'write', 'delete'],
  events: [
    'workspace.activated',
    'workspace.file.written',
    'workspace.file.replaced',
    'workspace.file.deleted',
    'workspace.directory.created',
    'workspace.path.copied',
    'workspace.path.moved',
  ],
  capabilities: [
    {
      id: 'workspace.root.get',
      moduleId: 'workspace',
      title: 'Get workspace root',
      description: 'Return the exact authoritative filesystem path of the active Monarch workspace.',
      risk: 'read',
      agent: {
        tags: ['workspace', 'filesystem', 'discovery', 'read'],
        effects: [{
          kind: 'workspace-root-observation',
          description: 'Returns the configured workspace root without reading file contents.',
          targetScope: 'workspace',
        }],
        idempotency: 'idempotent',
        reversibility: 'automatic',
        effectProfile: {
          mutation: 'none',
          targetScope: 'workspace',
          reversibility: 'automatic',
          privilege: 'normal',
          dataSensitivity: 'private',
          communication: 'none',
          financialImpact: false,
          identityImpact: false,
          securityImpact: false,
        },
        supportedSources: ['desktop', 'voice', 'telegram', 'api', 'system', 'smoke'],
        estimatedLatency: 'instant',
        computeClass: 'light',
        cancellation: 'unsupported',
        verification: [{
          kind: 'schema',
          description: 'The result must contain the authoritative workspace root.',
        }],
        examples: [{ goal: 'Locate the active project root before reading files.' }],
      },
      routing: {
        aliases: ['workspace root', 'workspace path', 'путь рабочего пространства', 'где находится рабочее пространство'],
        keywords: ['workspace', 'root', 'path', 'location', 'рабочее пространство', 'путь', 'расположение'],
        examples: ['where is the workspace', 'укажи точный путь рабочего пространства'],
        intentKinds: ['workspace.info', 'file.operation'],
      },
      inputSchema: {
        type: 'object',
        properties: {},
        additionalProperties: false,
      },
    },
    {
      id: 'workspace.files.read',
      moduleId: 'workspace',
      title: 'Read file',
      description: 'Read a text file inside the allowed workspace roots.',
      risk: 'read',
      agent: {
        tags: ['workspace', 'filesystem', 'file', 'read'],
        preconditions: [{
          kind: 'workspace-confined-path',
          description: 'The requested path must resolve inside an allowed workspace root.',
        }],
        effects: [{
          kind: 'file-content-observation',
          description: 'Returns bounded text content without changing the file.',
          targetScope: 'workspace',
        }],
        idempotency: 'idempotent',
        reversibility: 'automatic',
        effectProfile: {
          mutation: 'none',
          targetScope: 'workspace',
          reversibility: 'automatic',
          privilege: 'normal',
          dataSensitivity: 'private',
          communication: 'none',
          financialImpact: false,
          identityImpact: false,
          securityImpact: false,
        },
        supportedSources: ['desktop', 'voice', 'telegram', 'api', 'system', 'smoke'],
        estimatedLatency: 'short',
        computeClass: 'light',
        cancellation: 'unsupported',
        verification: [{
          kind: 'schema',
          description: 'The observation must identify the resolved path and bounded file content.',
        }],
        examples: [{ path: 'package.json', purpose: 'Inspect project metadata.' }],
      },
      routing: {
        aliases: ['read file', 'show file', 'open file', 'прочитай файл', 'прочитать файл', 'открой файл', 'открыть файл', 'покажи файл'],
        keywords: ['read', 'show', 'open', 'file', 'workspace', 'прочитай', 'прочитать', 'открой', 'открыть', 'покажи', 'показать', 'файл', 'файла', 'путь'],
        examples: ['read file package.json', 'прочитай package.json', 'можешь прочитать package.json'],
        intentKinds: ['file.read', 'file.operation'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          path: { type: 'string' },
          maxBytes: { type: 'number' },
        },
        required: ['path'],
        additionalProperties: false,
      },
    },
    {
      id: 'workspace.files.list',
      moduleId: 'workspace',
      title: 'List files',
      description: 'List files and directories inside an allowed workspace root.',
      risk: 'read',
      agent: {
        tags: ['workspace', 'filesystem', 'directory', 'list', 'read'],
        preconditions: [{
          kind: 'workspace-confined-path',
          description: 'The requested directory must resolve inside an allowed workspace root.',
        }],
        effects: [{
          kind: 'directory-listing-observation',
          description: 'Returns a bounded directory listing without changing the workspace.',
          targetScope: 'workspace',
        }],
        idempotency: 'idempotent',
        reversibility: 'automatic',
        effectProfile: {
          mutation: 'none',
          targetScope: 'workspace',
          reversibility: 'automatic',
          privilege: 'normal',
          dataSensitivity: 'private',
          communication: 'none',
          financialImpact: false,
          identityImpact: false,
          securityImpact: false,
        },
        supportedSources: ['desktop', 'voice', 'telegram', 'api', 'system', 'smoke'],
        estimatedLatency: 'short',
        computeClass: 'light',
        cancellation: 'unsupported',
        verification: [{
          kind: 'schema',
          description: 'The observation must contain a bounded list of workspace entries.',
        }],
        examples: [{ path: 'src', purpose: 'Discover implementation files.' }],
      },
      routing: {
        aliases: ['list files', 'show files', 'workspace files', 'покажи файлы', 'список файлов', 'просмотри папки', 'перечисли папки'],
        keywords: ['list', 'show', 'view', 'files', 'folder', 'directory', 'workspace', 'покажи', 'просмотри', 'посмотри', 'перечисли', 'список', 'файлы', 'папка', 'директория'],
        examples: ['list files in src', 'покажи файлы в src', 'просмотри названия папок в корневой папке'],
        intentKinds: ['file.list', 'file.operation'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          path: { type: 'string' },
          recursive: { type: 'boolean' },
          limit: { type: 'number' },
          entryType: { type: 'string' },
          extension: { type: 'string' },
        },
        additionalProperties: false,
      },
    },
    {
      id: 'workspace.files.search',
      moduleId: 'workspace',
      title: 'Search files',
      description: 'Search text files inside an allowed workspace root.',
      risk: 'read',
      agent: {
        tags: ['workspace', 'filesystem', 'search', 'read'],
        preconditions: [{
          kind: 'workspace-confined-path',
          description: 'The search root must resolve inside an allowed workspace root.',
        }],
        effects: [{
          kind: 'file-search-observation',
          description: 'Returns bounded matches without changing searched files.',
          targetScope: 'workspace',
        }],
        idempotency: 'idempotent',
        reversibility: 'automatic',
        effectProfile: {
          mutation: 'none',
          targetScope: 'workspace',
          reversibility: 'automatic',
          privilege: 'normal',
          dataSensitivity: 'private',
          communication: 'none',
          financialImpact: false,
          identityImpact: false,
          securityImpact: false,
        },
        supportedSources: ['desktop', 'voice', 'telegram', 'api', 'system', 'smoke'],
        estimatedLatency: 'short',
        computeClass: 'medium',
        cancellation: 'unsupported',
        verification: [{
          kind: 'schema',
          description: 'The observation must contain bounded search matches and their paths.',
        }],
        examples: [{ query: 'submitIntentJob', path: 'src', purpose: 'Find a live call path.' }],
      },
      routing: {
        aliases: ['search files', 'find in files', 'grep files', 'найди в файлах', 'поиск по файлам'],
        keywords: ['search', 'find', 'grep', 'files', 'workspace', 'найди', 'ищи', 'поиск', 'файлах', 'файлы'],
        examples: ['search files for router', 'найди в файлах AssistantModule'],
        intentKinds: ['file.search', 'file.operation'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          query: { type: 'string' },
          path: { type: 'string' },
          limit: { type: 'number' },
        },
        required: ['query'],
        additionalProperties: false,
      },
    },
    {
      id: 'workspace.files.write',
      moduleId: 'workspace',
      title: 'Write file',
      description: 'Write a text file inside the allowed workspace roots.',
      risk: 'write',
      agent: {
        tags: ['workspace', 'filesystem', 'file', 'write', 'mutation'],
        preconditions: [{
          kind: 'workspace-confined-path',
          description: 'The target path must resolve inside an allowed workspace root.',
        }],
        effects: [{
          kind: 'file-write',
          description: 'Creates or replaces bounded text content at a workspace-confined path.',
          targetScope: 'workspace',
        }],
        idempotency: 'conditional',
        reversibility: 'manual',
        effectProfile: {
          mutation: 'persistent',
          targetScope: 'workspace',
          reversibility: 'manual',
          privilege: 'normal',
          dataSensitivity: 'private',
          communication: 'none',
          financialImpact: false,
          identityImpact: false,
          securityImpact: false,
        },
        supportedSources: ['desktop', 'voice', 'telegram', 'api', 'system', 'smoke'],
        estimatedLatency: 'short',
        computeClass: 'light',
        cancellation: 'supported',
        verification: [{
          kind: 'read-after-write',
          description: 'A deterministic read must confirm the target exists with the expected content.',
          required: true,
        }],
        examples: [{ path: 'runtime/report.md', purpose: 'Persist a generated workspace report.' }],
      },
      routing: {
        aliases: ['write file', 'create file', 'save file', 'создай файл', 'запиши файл', 'сохрани файл'],
        keywords: ['write', 'create', 'save', 'file', 'workspace', 'создай', 'запиши', 'сохрани', 'файл'],
        examples: ['write file runtime/example.txt', 'создай файл runtime/example.txt'],
        intentKinds: ['file.write', 'file.generation'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          path: { type: 'string' },
          content: { type: 'string' },
          overwrite: { type: 'boolean' },
        },
        required: ['path', 'content'],
        additionalProperties: false,
      },
    },
    {
      id: 'workspace.files.append',
      moduleId: 'workspace',
      title: 'Append file',
      description: 'Append bounded text to a file inside the allowed workspace roots.',
      risk: 'write',
      routing: {
        aliases: ['append file', 'допиши файл', 'добавь в файл'],
        keywords: ['append', 'add', 'file', 'допиши', 'добавь', 'файл'],
        examples: ['допиши файл runtime/log.txt с текстом готово'],
        intentKinds: ['file.write', 'file.operation'],
      },
      inputSchema: {
        type: 'object',
        properties: { path: { type: 'string' }, content: { type: 'string' } },
        required: ['path', 'content'],
        additionalProperties: false,
      },
    },
    {
      id: 'workspace.files.mkdir',
      moduleId: 'workspace',
      title: 'Create directory',
      description: 'Create a directory tree inside the allowed workspace roots.',
      risk: 'write',
      routing: {
        aliases: ['create folder', 'mkdir', 'создай папку'],
        keywords: ['create', 'folder', 'directory', 'mkdir', 'создай', 'папку', 'директорию'],
        examples: ['создай папку artifacts/generated/demo'],
        intentKinds: ['file.write', 'file.operation'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          path: { type: 'string' },
          ensureUnique: { type: 'boolean' },
        },
        required: ['path'],
        additionalProperties: false,
      },
    },
    {
      id: 'workspace.files.copy',
      moduleId: 'workspace',
      title: 'Copy file or directory',
      description: 'Copy a bounded file tree without following symbolic links.',
      risk: 'write',
      routing: {
        aliases: ['copy file', 'copy folder', 'скопируй файл', 'скопируй папку'],
        keywords: ['copy', 'duplicate', 'file', 'folder', 'скопируй', 'дублируй', 'файл', 'папку'],
        examples: ['скопируй папку "runtime/a" в "runtime/b"'],
        intentKinds: ['file.write', 'file.operation'],
      },
      inputSchema: {
        type: 'object',
        properties: { path: { type: 'string' }, targetPath: { type: 'string' } },
        required: ['path', 'targetPath'],
        additionalProperties: false,
      },
    },
    {
      id: 'workspace.files.move',
      moduleId: 'workspace',
      title: 'Move file or directory',
      description: 'Move or rename a file or directory inside the allowed workspace roots.',
      risk: 'delete',
      routing: {
        aliases: ['move file', 'rename file', 'перемести файл', 'переименуй папку'],
        keywords: ['move', 'rename', 'file', 'folder', 'перемести', 'переименуй', 'файл', 'папку'],
        examples: ['перемести файл "runtime/a.txt" в "runtime/b.txt"'],
        intentKinds: ['file.delete', 'file.operation'],
      },
      inputSchema: {
        type: 'object',
        properties: { path: { type: 'string' }, targetPath: { type: 'string' } },
        required: ['path', 'targetPath'],
        additionalProperties: false,
      },
    },
    {
      id: 'workspace.files.replace',
      moduleId: 'workspace',
      title: 'Replace file text',
      description: 'Replace one exact text fragment inside a text file in the allowed workspace roots.',
      risk: 'write',
      routing: {
        aliases: ['replace in file', 'replace file text', 'замени в файле', 'заменить текст в файле'],
        keywords: ['replace', 'edit', 'file', 'workspace', 'замени', 'заменить', 'исправь', 'файл'],
        examples: ['replace in file runtime/example.txt "old" with "new"', 'замени в файле runtime/example.txt "old" на "new"'],
        intentKinds: ['file.write', 'file.operation'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          path: { type: 'string' },
          oldText: { type: 'string' },
          newText: { type: 'string' },
        },
        required: ['path', 'oldText', 'newText'],
        additionalProperties: false,
      },
    },
    {
      id: 'workspace.files.delete',
      moduleId: 'workspace',
      title: 'Delete file',
      description: 'Delete a file inside the allowed workspace roots.',
      risk: 'delete',
      routing: {
        aliases: ['delete file', 'remove file', 'удали файл'],
        keywords: ['delete', 'remove', 'file', 'workspace', 'удали', 'сотри', 'файл'],
        examples: ['delete file runtime/example.txt', 'удали файл runtime/example.txt'],
        intentKinds: ['file.delete', 'file.operation'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          path: { type: 'string' },
        },
        required: ['path'],
        additionalProperties: false,
      },
    },
  ],
};
