import type { MonarchModuleManifest } from '../../core';

export const systemShellManifest: MonarchModuleManifest = {
  id: 'system-shell',
  name: 'Monarch System Shell',
  version: '0.1.0',
  kind: 'tooling',
  description: 'Exact argv process fallback for Agent Runtime with bounded output, cancellation, receipts, and immutable Safe exclusion.',
  owns: ['system shell', 'terminal fallback', 'process execution', 'терминал', 'команды'],
  permissions: ['execute'],
  events: ['system-shell.activated', 'system-shell.completed'],
  capabilities: [{
    id: 'system.shell.run',
    moduleId: 'system-shell',
    title: 'Run one exact process without an implicit shell',
    description: 'Execute an exact executable and argv in an exact cwd with timeout and declared network posture. Every call is receipt-bound and defaults to an exact action-card.',
    risk: 'execute',
    agent: {
      tags: ['system', 'shell', 'terminal', 'process', 'fallback', 'argv'],
      preconditions: [{
        kind: 'exact-process-input',
        description: 'Executable, argv, cwd, timeout, and network posture must be explicit; Monarch Safe references are always rejected.',
      }],
      effects: [{
        kind: 'process-execution',
        description: 'Starts one non-elevated child process without shell interpolation.',
        targetScope: 'device',
      }],
      idempotency: 'non-idempotent',
      reversibility: 'manual',
      effectProfile: {
        mutation: 'persistent',
        targetScope: 'device',
        reversibility: 'manual',
        privilege: 'elevated',
        dataSensitivity: 'private',
        communication: 'internet',
        financialImpact: false,
        identityImpact: false,
        securityImpact: true,
      },
      supportedSources: ['desktop', 'coder', 'voice', 'telegram', 'api', 'system', 'smoke'],
      estimatedLatency: 'long',
      computeClass: 'heavy',
      cancellation: 'supported',
      verification: [{
        kind: 'runtime-status',
        description: 'Kernel receives exit state, bounded output hashes, duration, timeout state, and exact argv digest.',
        required: true,
        predicate: { kind: 'status', target: 'result.output.receiptVerified', value: true },
      }],
      examples: [{ goal: 'Run an exact command when no narrower registered capability exists.' }],
    },
    routing: {
      aliases: ['run shell command', 'terminal fallback', 'выполни команду в терминале'],
      keywords: ['shell', 'terminal', 'command', 'execute', 'process', 'терминал', 'команда', 'выполни'],
      examples: ['Выполни Get-Date через powershell.exe'],
      intentKinds: ['system.execute', 'terminal'],
    },
    inputSchema: {
      type: 'object',
      properties: {
        executable: { type: 'string', minLength: 1, maxLength: 1024 },
        args: { type: 'array', maxItems: 128, items: { type: 'string', maxLength: 8192 } },
        cwd: { type: 'string', minLength: 1, maxLength: 2048 },
        timeoutMs: { type: 'integer', minimum: 100, maximum: 600000 },
        networkPosture: { type: 'string', enum: ['offline', 'inherit', 'allowed'] },
        maxOutputBytes: { type: 'integer', minimum: 1024, maximum: 1048576 },
      },
      required: ['executable', 'args', 'cwd', 'timeoutMs', 'networkPosture'],
      additionalProperties: false,
    },
    outputSchema: {
      type: 'object',
      properties: {
        executable: { type: 'string' },
        cwd: { type: 'string' },
        argvSha256: { type: 'string' },
        exitCode: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
        stdout: { type: 'string' },
        stderr: { type: 'string' },
        stdoutSha256: { type: 'string' },
        stderrSha256: { type: 'string' },
        timedOut: { type: 'boolean' },
        cancelled: { type: 'boolean' },
        truncated: { type: 'boolean' },
        durationMs: { type: 'integer' },
        networkPosture: { type: 'string' },
        networkIsolationEnforced: { type: 'boolean' },
        receiptVerified: { type: 'boolean' },
      },
      required: ['executable', 'cwd', 'argvSha256', 'exitCode', 'stdout', 'stderr', 'stdoutSha256', 'stderrSha256', 'timedOut', 'cancelled', 'truncated', 'durationMs', 'networkPosture', 'networkIsolationEnforced', 'receiptVerified'],
      additionalProperties: false,
    },
  }],
};
