import type { MonarchModuleManifest } from '../../core';

export const studioManifest: MonarchModuleManifest = {
  id: 'studio',
  name: 'Monarch Studio',
  version: '0.1.0',
  stage: 'alpha',
  kind: 'domain',
  parentSuiteId: 'monarch-modules',
  description: 'Local-first photo and video creation workspace inside Monarch Modules.',
  owns: [
    'monarch studio',
    'photo editor',
    'video editor',
    'image editing',
    'media project',
    'фоторедактор',
    'видеоредактор',
    'редактор фото',
    'редактор видео',
  ],
  permissions: ['none', 'read', 'write'],
  dependencies: ['monarch-modules'],
  events: [
    'studio.activated',
    'studio.project.created',
    'studio.project.opened',
    'studio.project.saved',
    'studio.edit.applied',
    'studio.media.probed',
    'studio.photo.exported',
  ],
  capabilities: [
    {
      id: 'studio.features.list',
      moduleId: 'studio',
      title: 'List Studio features',
      description: 'Describe available, planned, and optional Monarch Studio editing features.',
      risk: 'read',
      routing: {
        aliases: ['monarch studio', 'open studio', 'открой studio'],
        keywords: ['studio', 'photo editor', 'video editor', 'фоторедактор', 'видеоредактор'],
        examples: ['what can Monarch Studio do', 'что умеет Monarch Studio'],
        intentKinds: ['studio.features'],
      },
      inputSchema: {
        type: 'object',
        properties: {},
        additionalProperties: false,
      },
    },
    {
      id: 'studio.project.open',
      moduleId: 'studio',
      title: 'Open Studio project',
      description: 'Read and validate a Studio project from the configured Studio projects root.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {
          path: { type: 'string' },
        },
        required: ['path'],
        additionalProperties: false,
      },
    },
    {
      id: 'studio.project.create',
      moduleId: 'studio',
      title: 'Create Studio project',
      description: 'Create a versioned local Monarch Studio photo or video project.',
      risk: 'write',
      routing: {
        aliases: ['new studio project', 'создай проект studio'],
        keywords: ['studio', 'project', 'photo', 'video', 'проект', 'фото', 'видео'],
        examples: ['create a photo project in Monarch Studio', 'создай видеопроект в Monarch Studio'],
        intentKinds: ['studio.project.create'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          mode: { type: 'string', enum: ['photo', 'video'] },
          width: { type: 'number' },
          height: { type: 'number' },
          background: { type: 'string' },
          fps: { type: 'number' },
          durationMs: { type: 'number' },
        },
        required: ['name', 'mode'],
        additionalProperties: false,
      },
    },
    {
      id: 'studio.project.validate',
      moduleId: 'studio',
      title: 'Validate Studio project',
      description: 'Validate a Monarch Studio project document without changing it.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {
          project: { type: 'object' },
        },
        required: ['project'],
        additionalProperties: false,
      },
    },
    {
      id: 'studio.edit.apply',
      moduleId: 'studio',
      title: 'Apply Studio edit',
      description: 'Apply a validated photo, video, or project edit to an in-memory Studio project with history.',
      risk: 'none',
      inputSchema: {
        type: 'object',
        properties: {
          project: { type: 'object' },
          edit: { type: 'object' },
        },
        required: ['project', 'edit'],
        additionalProperties: false,
      },
    },
    {
      id: 'studio.history.step',
      moduleId: 'studio',
      title: 'Undo or redo Studio edit',
      description: 'Move through the bounded non-destructive Studio project history.',
      risk: 'none',
      inputSchema: {
        type: 'object',
        properties: {
          project: { type: 'object' },
          direction: { type: 'string', enum: ['undo', 'redo'] },
        },
        required: ['project', 'direction'],
        additionalProperties: false,
      },
    },
    {
      id: 'studio.project.save',
      moduleId: 'studio',
      title: 'Save Studio project',
      description: 'Validate and atomically save a Studio project inside the configured Studio projects root.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: {
          project: { type: 'object' },
          path: { type: 'string' },
        },
        required: ['project'],
        additionalProperties: false,
      },
    },
    {
      id: 'studio.media.probe',
      moduleId: 'studio',
      title: 'Inspect media file',
      description: 'Read local video or audio metadata through the pinned Mediabunny adapter.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {
          path: { type: 'string' },
        },
        required: ['path'],
        additionalProperties: false,
      },
    },
    {
      id: 'studio.photo.export',
      moduleId: 'studio',
      title: 'Export Studio photo',
      description: 'Render and write a Studio photo project as PNG or JPEG through Fabric.js.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: {
          project: { type: 'object' },
          format: { type: 'string', enum: ['png', 'jpeg'] },
          filename: { type: 'string' },
          quality: { type: 'number' },
        },
        required: ['project'],
        additionalProperties: false,
      },
    },
    {
      id: 'studio.export.plan',
      moduleId: 'studio',
      title: 'Plan Studio export',
      description: 'Choose a local export pipeline and expose optional dependency or license requirements.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {
          mode: { type: 'string', enum: ['photo', 'video'] },
          format: { type: 'string' },
          templateDriven: { type: 'boolean' },
          preferBrowser: { type: 'boolean' },
        },
        required: ['mode', 'format'],
        additionalProperties: false,
      },
    },
  ],
};
