import type { MonarchModuleManifest } from '../../core';

export const voiceManifest: MonarchModuleManifest = {
  id: 'voice',
  name: 'Monarch Voice',
  version: '1.0.0',
  kind: 'runtime',
  description: 'Standalone local voice assistant runtime with STT/TTS, bounded conversation sessions, routing, and delegated actions.',
  owns: ['voice', 'speech', 'stt', 'tts', 'microphone', 'voice sessions', 'voice routing'],
  permissions: ['read', 'execute'],
  events: [
    'voice.activated',
    'voice.bridge.started',
    'voice.bridge.stopped',
    'voice.bridge.event',
    'voice.transcribe.completed',
    'voice.mode.classified',
    'voice.mode.ready',
    'voice.mode.released',
    'voice.mode.responded',
    'voice.mode.session.started',
    'voice.mode.session.completed',
    'voice.mode.session.closed',
    'voice.mode.scripted.executed',
    'voice.mode.scripted.clarification',
    'voice.mode.scripted.unsupported',
  ],
  capabilities: [
    {
      id: 'voice.status',
      moduleId: 'voice',
      title: 'Voice status',
      description: 'Show configured voice bridge commands and running state.',
      risk: 'read',
      routing: {
        aliases: ['voice status', 'speech status'],
        keywords: ['voice', 'speech', 'stt', 'tts', 'microphone', 'status'],
        examples: ['show voice status'],
        intentKinds: ['voice.read'],
      },
      inputSchema: {
        type: 'object',
        properties: {},
        additionalProperties: false,
      },
    },
    {
      id: 'voice.mode.classify',
      moduleId: 'voice',
      title: 'Classify a voice-mode turn',
      description: 'Route a short voice transcript to scripted, Micro, Lite, or Fast without loading a model.',
      risk: 'read',
      routing: {
        aliases: ['classify voice command', 'voice mode route'],
        keywords: ['voice', 'route', 'command', 'fast'],
        examples: ['classify this voice command'],
        intentKinds: ['voice.read'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          text: { type: 'string' },
          sessionId: { type: 'string', minLength: 24, maxLength: 96 },
        },
        required: ['text'],
        additionalProperties: false,
      },
    },
    {
      id: 'voice.mode.session.start',
      moduleId: 'voice',
      title: 'Start a voice conversation session',
      description: 'Create an ephemeral bounded Voice-owned conversation context for follow-up turns.',
      risk: 'read',
      routing: {
        aliases: ['start voice session'],
        keywords: ['voice', 'session', 'context'],
        examples: ['start a contextual voice session'],
        intentKinds: ['voice.read'],
      },
      inputSchema: {
        type: 'object',
        properties: {},
        additionalProperties: false,
      },
    },
    {
      id: 'voice.mode.session.complete',
      moduleId: 'voice',
      title: 'Complete a voice conversation turn',
      description: 'Commit one completed user/assistant exchange to the ephemeral Voice session.',
      risk: 'read',
      routing: {
        aliases: ['complete voice turn'],
        keywords: ['voice', 'session', 'turn', 'context'],
        examples: ['remember the completed voice turn'],
        intentKinds: ['voice.read'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          sessionId: { type: 'string', minLength: 24, maxLength: 96 },
          turnId: { type: 'string', minLength: 16, maxLength: 64 },
          response: { type: 'string', minLength: 1, maxLength: 2000 },
          actionId: { type: 'string', minLength: 1, maxLength: 120 },
        },
        required: ['sessionId', 'turnId', 'response'],
        additionalProperties: false,
      },
    },
    {
      id: 'voice.mode.session.close',
      moduleId: 'voice',
      title: 'Close a voice conversation session',
      description: 'Forget the ephemeral Voice-owned context when the voice surface closes.',
      risk: 'read',
      routing: {
        aliases: ['close voice session'],
        keywords: ['voice', 'session', 'close', 'forget'],
        examples: ['close the current voice session'],
        intentKinds: ['voice.read'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          sessionId: { type: 'string', minLength: 24, maxLength: 96 },
        },
        required: ['sessionId'],
        additionalProperties: false,
      },
    },
    {
      id: 'voice.mode.prepare',
      moduleId: 'voice',
      title: 'Prepare voice runtimes',
      description: 'Prepare local streaming STT; optionally load only the isolated Lite profile after STT.',
      risk: 'read',
      routing: {
        aliases: ['prepare voice mode', 'warm voice lite'],
        keywords: ['voice', 'prepare', 'warm', 'lite', 'local'],
        examples: ['prepare the fast local voice model'],
        intentKinds: ['voice.read'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          profiles: {
            type: 'array',
            items: { type: 'string', enum: ['lite'] },
            minItems: 1,
            maxItems: 1,
            uniqueItems: true,
          },
        },
        additionalProperties: false,
      },
    },
    {
      id: 'voice.mode.release',
      moduleId: 'voice',
      title: 'Release voice-mode local LLM',
      description: 'Stop the lazy isolated Lite worker when the Voice Mode surface closes.',
      risk: 'read',
      routing: {
        aliases: ['release voice mode', 'unload voice lite'],
        keywords: ['voice', 'release', 'unload', 'lite', 'local'],
        examples: ['release the local voice model'],
        intentKinds: ['voice.read'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          profiles: {
            type: 'array',
            items: { type: 'string', enum: ['lite'] },
            minItems: 1,
            maxItems: 1,
            uniqueItems: true,
          },
        },
        additionalProperties: false,
      },
    },
    {
      id: 'voice.mode.respond',
      moduleId: 'voice',
      title: 'Generate a local voice response',
      description: 'Generate a short spoken response in one lazy isolated Lite worker; legacy Micro requests alias to Lite.',
      risk: 'read',
      routing: {
        aliases: ['voice lite response', 'quick voice response'],
        keywords: ['voice', 'lite', 'respond', 'quick', 'local'],
        examples: ['answer this short voice request locally'],
        intentKinds: ['voice.read'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          profile: { type: 'string', enum: ['micro', 'lite'] },
          text: { type: 'string', minLength: 1, maxLength: 1200 },
        },
        required: ['profile', 'text'],
        additionalProperties: false,
      },
    },
    {
      id: 'voice.mode.execute-scripted',
      moduleId: 'voice',
      title: 'Execute a scripted voice command',
      description: 'Reclassify and execute only a trusted model-free voice handler.',
      risk: 'read',
      routing: {
        aliases: ['execute scripted voice', 'voice command locally'],
        keywords: ['voice', 'scripted', 'time', 'listen', 'local'],
        examples: ['execute this deterministic voice command'],
        intentKinds: ['voice.read'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          text: { type: 'string', minLength: 1, maxLength: 1200 },
        },
        required: ['text'],
        additionalProperties: false,
      },
    },
    {
      id: 'voice.transcribe.audio',
      moduleId: 'voice',
      title: 'Transcribe recorded audio',
      description: 'Transcribe a short recorded audio clip through a configured local one-shot STT command.',
      risk: 'read',
      routing: {
        aliases: ['transcribe audio', 'voice input', 'speech to text'],
        keywords: ['voice', 'speech', 'stt', 'microphone', 'transcribe', 'dictation'],
        examples: ['transcribe this voice input'],
        intentKinds: ['voice.read'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          audioBase64: { type: 'string' },
          mimeType: { type: 'string' },
          language: { type: 'string' },
          durationMs: { type: 'number' },
        },
        required: ['audioBase64'],
        additionalProperties: false,
      },
    },
    {
      id: 'voice.transcribe.stream.start',
      moduleId: 'voice',
      title: 'Start direct PCM transcription',
      description: 'Open a bounded local streaming STT session without persisting raw audio.',
      risk: 'read',
      routing: {
        aliases: ['start streaming transcription'],
        keywords: ['voice', 'stt', 'pcm', 'stream'],
        examples: ['start local PCM transcription'],
        intentKinds: ['voice.read'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          language: { type: 'string', enum: ['ru-RU', 'uk-UA', 'bg-BG', 'en-US'] },
          sampleRate: { type: 'number', minimum: 8000, maximum: 48000 },
        },
        required: ['language', 'sampleRate'],
        additionalProperties: false,
      },
    },
    {
      id: 'voice.transcribe.stream.push',
      moduleId: 'voice',
      title: 'Push direct PCM audio',
      description: 'Decode one ordered, bounded PCM16 batch in the resident local STT worker.',
      risk: 'read',
      routing: {
        aliases: ['push streaming audio'],
        keywords: ['voice', 'stt', 'pcm', 'batch'],
        examples: ['decode next PCM batch'],
        intentKinds: ['voice.read'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          sessionId: { type: 'string', minLength: 24, maxLength: 160 },
          sequence: { type: 'number', minimum: 0 },
          pcmBase64: { type: 'string', minLength: 4, maxLength: 98304 },
        },
        required: ['sessionId', 'sequence', 'pcmBase64'],
        additionalProperties: false,
      },
    },
    {
      id: 'voice.transcribe.stream.finish',
      moduleId: 'voice',
      title: 'Finish direct PCM transcription',
      description: 'Finalize the resident local STT stream and return its transcript and latency telemetry.',
      risk: 'read',
      routing: {
        aliases: ['finish streaming transcription'],
        keywords: ['voice', 'stt', 'pcm', 'final'],
        examples: ['finish local PCM transcription'],
        intentKinds: ['voice.read'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          sessionId: { type: 'string', minLength: 24, maxLength: 160 },
          captureStoppedAtEpochMs: { type: 'number', minimum: 0 },
        },
        required: ['sessionId'],
        additionalProperties: false,
      },
    },
    {
      id: 'voice.transcribe.stream.cancel',
      moduleId: 'voice',
      title: 'Cancel direct PCM transcription',
      description: 'Release a local streaming STT session without retaining raw PCM or a transcript.',
      risk: 'read',
      routing: {
        aliases: ['cancel streaming transcription'],
        keywords: ['voice', 'stt', 'pcm', 'cancel'],
        examples: ['cancel local PCM transcription'],
        intentKinds: ['voice.read'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          sessionId: { type: 'string', minLength: 24, maxLength: 160 },
        },
        required: ['sessionId'],
        additionalProperties: false,
      },
    },
    {
      id: 'voice.bridge.start',
      moduleId: 'voice',
      title: 'Start voice bridge',
      description: 'Start a configured STT or TTS bridge process.',
      risk: 'execute',
      routing: {
        aliases: ['start voice bridge', 'start stt', 'start tts'],
        keywords: ['start', 'voice', 'bridge', 'stt', 'tts'],
        examples: ['start stt bridge'],
        intentKinds: ['voice.start'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          bridge: { type: 'string' },
        },
        required: ['bridge'],
        additionalProperties: false,
      },
    },
    {
      id: 'voice.bridge.stop',
      moduleId: 'voice',
      title: 'Stop voice bridge',
      description: 'Stop a managed STT or TTS bridge process.',
      risk: 'execute',
      routing: {
        aliases: ['stop voice bridge', 'stop stt', 'stop tts'],
        keywords: ['stop', 'voice', 'bridge', 'stt', 'tts'],
        examples: ['stop stt bridge'],
        intentKinds: ['voice.stop'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          bridge: { type: 'string' },
        },
        required: ['bridge'],
        additionalProperties: false,
      },
    },
  ],
};
