import type { MonarchModuleManifest } from '../../core';

export const memoryManifest: MonarchModuleManifest = {
  id: 'memory',
  name: 'Monarch Memory',
  version: '0.1.0',
  kind: 'system',
  description: 'Local file-backed memory service for early Monarch kernel flows.',
  owns: ['memory', 'память', 'remember', 'recall', 'facts'],
  permissions: ['read', 'write'],
  events: [
    'memory.activated',
    'memory.record.created',
    'memory.record.updated',
    'memory.record.forgotten',
  ],
  capabilities: [
    {
      id: 'memory.remember',
      moduleId: 'memory',
      title: 'Remember fact',
      description: 'Store a local memory record.',
      risk: 'write',
      routing: {
        aliases: ['remember', 'remember fact', 'save memory', 'store memory', 'запомни', 'сохрани в память'],
        keywords: ['memory', 'remember', 'save', 'store', 'fact', 'facts', 'память', 'запомни', 'сохрани'],
        examples: [
          'remember that Monarch should stay local first',
          'save this in memory',
          'запомни в память',
        ],
        intentKinds: ['memory.write', 'remember'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          text: { type: 'string' },
          source: { type: 'string' },
          type: { type: 'string' },
          title: { type: 'string' },
          tags: { type: 'array', items: { type: 'string' } },
          category: { type: 'string' },
          tier: { type: 'string' },
          importance: { type: 'number' },
          priority: { type: 'number' },
          pinned: { type: 'boolean' },
          expiresAt: { type: 'string' },
          relatedFiles: { type: 'array', items: { type: 'string' } },
          relatedModules: { type: 'array', items: { type: 'string' } },
        },
        required: ['text'],
        additionalProperties: false,
      },
    },
    {
      id: 'memory.search',
      moduleId: 'memory',
      title: 'Search memory',
      description: 'Search local memory records.',
      risk: 'read',
      routing: {
        aliases: ['recall', 'search memory', 'find memory', 'вспомни', 'найди в памяти'],
        keywords: ['memory', 'recall', 'search', 'find', 'query', 'память', 'вспомни', 'найди'],
        examples: [
          'recall Monarch',
          'search memory for project notes',
          'вспомни Monarch',
        ],
        intentKinds: ['memory.read', 'memory.search'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          query: { type: 'string' },
          limit: { type: 'number' },
          type: { type: 'string' },
          types: { type: 'array', items: { type: 'string' } },
          tags: { type: 'array', items: { type: 'string' } },
          localOnly: { type: 'boolean' },
          includeClosed: { type: 'boolean' },
          includeExpired: { type: 'boolean' },
        },
        required: ['query'],
        additionalProperties: false,
      },
    },
    {
      id: 'memory.list',
      moduleId: 'memory',
      title: 'List memory',
      description: 'List recent local memory records.',
      risk: 'read',
      routing: {
        aliases: ['list memory', 'show memory', 'recent memories', 'покажи память', 'что ты помнишь'],
        keywords: ['memory', 'list', 'recent', 'show', 'records', 'память', 'помнишь', 'покажи'],
        examples: [
          'list memory',
          'show recent memories',
        ],
        intentKinds: ['memory.read', 'memory.list'],
      },
      inputSchema: {
        type: 'object',
        properties: {
          limit: { type: 'number' },
          type: { type: 'string' },
          types: { type: 'array', items: { type: 'string' } },
          tags: { type: 'array', items: { type: 'string' } },
          includeClosed: { type: 'boolean' },
          includeExpired: { type: 'boolean' },
        },
        additionalProperties: false,
      },
    },
    {
      id: 'memory.update',
      moduleId: 'memory',
      title: 'Update memory',
      description: 'Edit a local memory record.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: {
          id: { type: 'string' },
          text: { type: 'string' },
          type: { type: 'string' },
          title: { type: 'string' },
          tags: { type: 'array', items: { type: 'string' } },
          category: { type: 'string' },
          tier: { type: 'string' },
          importance: { type: 'number' },
          priority: { type: 'number' },
          pinned: { type: 'boolean' },
          expiresAt: { type: 'string' },
          relatedFiles: { type: 'array', items: { type: 'string' } },
          relatedModules: { type: 'array', items: { type: 'string' } },
        },
        required: ['id'],
        additionalProperties: false,
      },
    },
    {
      id: 'memory.close_temporary',
      moduleId: 'memory',
      title: 'Close temporary memory',
      description: 'Mark a temporary memory/task record as closed without deleting durable history.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: { id: { type: 'string' } },
        required: ['id'],
        additionalProperties: false,
      },
    },
    {
      id: 'memory.forget',
      moduleId: 'memory',
      title: 'Forget memory',
      description: 'Remove one local memory record.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: { id: { type: 'string' } },
        required: ['id'],
        additionalProperties: false,
      },
    },
  ],
};
