import type { MonarchModuleManifest } from '../../core';

export const securityManifest: MonarchModuleManifest = {
  id: 'security',
  name: 'Monarch Security',
  version: '0.1.0',
  kind: 'runtime',
  description: 'Integrated local-first host security protector: sensors, policy, scan, audit integrity, and safe verification labs.',
  owns: [
    'security',
    'protection',
    'protector',
    'scan',
    'defender',
    'network security',
    'persistence',
    'audit integrity',
    'безопасность',
    'защита',
    'сканирование',
    'антивирус',
    'аудит безопасности',
  ],
  permissions: ['read', 'write', 'execute', 'device-control', 'security-sensitive'],
  events: [
    'security.activated',
    'security.status.checked',
    'security.incidents.read',
    'security.incident.changed',
    'security.quarantine.read',
    'security.quarantine.changed',
    'security.responses.read',
    'security.response.proposed',
    'security.response.evaluated',
    'security.response.approved',
    'security.response.actions.read',
    'security.response.service.status',
    'security.emergency.status',
    'security.emergency.resolved',
    'security.pin.status',
    'security.pin.changed',
    'security.pin.verified',
    'security.pin.recovered',
    'security.scan.completed',
    'security.protection.changed',
    'security.profile.changed',
    'security.model_policy.changed',
    'security.integrity.checked',
    'security.audit.tail_read',
    'security.report.generated',
    'security.network.center.read',
    'security.network.profile.changed',
    'security.benchmark.started',
    'security.benchmark.status',
    'security.benchmark.cancelled',
    'security.baseline.previewed',
    'security.simulation.created',
  ],
  capabilities: [
    {
      id: 'security.status',
      moduleId: 'security',
      title: 'Read security protector status',
      description: 'Read whether Monarch Security background protection is running and where its runtime files live.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {},
        additionalProperties: false,
      },
      routing: {
        aliases: ['security status', 'status security', 'protection status', 'protector status', 'статус security', 'статус защиты', 'статус безопасности'],
        keywords: ['security', 'protection', 'protector', 'status', 'безопасность', 'защита', 'статус'],
        examples: ['show security status', 'покажи статус Security', 'покажи статус защиты'],
        intentKinds: ['security.status', 'protector.status'],
      },
    },
    {
      id: 'security.diagnose',
      moduleId: 'security',
      title: 'Diagnose security runtime',
      description: 'Read model, resource, path, sensor, notification, and integrity settings for Monarch Security.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {},
        additionalProperties: false,
      },
      routing: {
        aliases: ['security diagnose', 'diagnose protection', 'диагностика защиты'],
        keywords: ['security', 'diagnose', 'runtime', 'settings', 'resources', 'безопасность', 'диагностика', 'настройки'],
        examples: ['diagnose Monarch Security', 'проверь диагностику защиты'],
        intentKinds: ['security.diagnose'],
      },
    },
    {
      id: 'security.profile.get',
      moduleId: 'security',
      title: 'Read Security strictness profile',
      description: 'Read the active Security observation and command-control strictness.',
      risk: 'read',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
      routing: {
        aliases: ['security level', 'security strictness', 'уровень строгости security'],
        keywords: ['security', 'profile', 'level', 'strictness', 'уровень', 'строгость'],
        examples: ['покажи уровень строгости Security'],
        intentKinds: ['security.profile'],
      },
    },
    {
      id: 'security.profile.set',
      moduleId: 'security',
      title: 'Change Security strictness profile',
      description: 'Set Security to off, minimal, balanced, strict, or maximum and safely reload monitoring.',
      risk: 'device-control',
      inputSchema: {
        type: 'object',
        properties: { level: { type: 'string', enum: ['off', 'minimal', 'balanced', 'strict', 'maximum'] } },
        required: ['level'],
        additionalProperties: false,
      },
      routing: {
        aliases: ['change security level', 'set security strictness', 'измени уровень security'],
        keywords: ['security', 'profile', 'level', 'strictness', 'режим', 'строгость'],
        examples: ['установи средний уровень Security'],
        intentKinds: ['security.profile.set'],
      },
    },
    {
      id: 'security.model_policy.get',
      moduleId: 'security',
      title: 'Read Oscar command security policy',
      description: 'Read whether Oscar may propose system commands and how confirmations are requested.',
      risk: 'read',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
      routing: {
        aliases: ['Oscar command security', 'LLM command policy', 'безопасность команд модели'],
        keywords: ['Oscar', 'LLM', 'model', 'commands', 'policy', 'модель', 'команды', 'безопасность'],
        examples: ['покажи параметры безопасности команд Oscar'],
        intentKinds: ['security.model_policy'],
      },
    },
    {
      id: 'security.model_policy.set',
      moduleId: 'security',
      title: 'Change Oscar command security policy',
      description: 'Enable or disable Oscar command proposals and choose adaptive or always-confirm behavior.',
      risk: 'device-control',
      inputSchema: {
        type: 'object',
        properties: {
          enabled: { type: 'boolean' },
          confirmationMode: { type: 'string', enum: ['adaptive', 'always'] },
        },
        required: ['enabled', 'confirmationMode'],
        additionalProperties: false,
      },
      routing: {
        aliases: ['change Oscar command security', 'set LLM command policy', 'измени безопасность команд модели'],
        keywords: ['Oscar', 'LLM', 'model', 'commands', 'policy', 'модель', 'команды', 'безопасность'],
        examples: ['всегда спрашивай перед командами Oscar'],
        intentKinds: ['security.model_policy.set'],
      },
    },
    {
      id: 'security.audit.tail',
      moduleId: 'security',
      title: 'Read security audit tail',
      description: 'Read recent Monarch Security audit log records.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {
          lines: { type: 'number' },
        },
        additionalProperties: false,
      },
      routing: {
        aliases: ['security audit', 'security logs', 'tail security audit', 'логи защиты', 'аудит безопасности'],
        keywords: ['security', 'audit', 'logs', 'tail', 'безопасность', 'аудит', 'логи'],
        examples: ['show security logs', 'покажи последние логи защиты'],
        intentKinds: ['security.audit', 'audit.read'],
      },
    },
    {
      id: 'security.integrity.verify',
      moduleId: 'security',
      title: 'Verify security integrity',
      description: 'Verify HMAC integrity for Monarch Security audit and state.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {},
        additionalProperties: false,
      },
      routing: {
        aliases: ['verify security integrity', 'security integrity', 'проверь целостность защиты'],
        keywords: ['security', 'integrity', 'hmac', 'audit', 'verify', 'безопасность', 'целостность', 'аудит'],
        examples: ['verify security integrity', 'проверь целостность аудита защиты'],
        intentKinds: ['security.integrity'],
      },
    },
    {
      id: 'security.incidents.list',
      moduleId: 'security',
      title: 'List security incidents',
      description: 'Read the latest durable Monarch Security incidents, risk scores, evidence families, and pending decisions.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {
          limit: { type: 'number' },
        },
        additionalProperties: false,
      },
      routing: {
        aliases: ['security incidents', 'incident inbox', 'инциденты безопасности', 'угрозы безопасности'],
        keywords: ['security', 'incident', 'threat', 'risk', 'decision', 'безопасность', 'инцидент', 'угроза', 'риск'],
        examples: ['show security incidents', 'покажи последние инциденты безопасности'],
        intentKinds: ['security.incidents', 'security.threats'],
      },
    },
    {
      id: 'security.incident.status',
      moduleId: 'security',
      title: 'Update security incident status',
      description: 'Acknowledge, resolve, or dismiss one incident after explicit user confirmation.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: {
          incidentId: { type: 'string' },
          status: { type: 'string', enum: ['acknowledged', 'resolved', 'dismissed'] },
          reason: { type: 'string' },
        },
        required: ['incidentId', 'status'],
        additionalProperties: false,
      },
    },
    {
      id: 'security.quarantine.list',
      moduleId: 'security',
      title: 'List quarantine records',
      description: 'Read active local quarantine records and vault integrity status.',
      risk: 'read',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
      routing: {
        aliases: ['security quarantine', 'карантин безопасности'],
        keywords: ['security', 'quarantine', 'isolation', 'безопасность', 'карантин', 'изоляция'],
        examples: ['show security quarantine', 'покажи карантин безопасности'],
        intentKinds: ['security.quarantine'],
      },
    },
    {
      id: 'security.quarantine.isolate',
      moduleId: 'security',
      title: 'Isolate file in quarantine',
      description: 'Move one explicitly confirmed local file into the integrity-checked quarantine vault.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: { path: { type: 'string' }, incidentId: { type: 'string' } },
        required: ['path'],
        additionalProperties: false,
      },
    },
    {
      id: 'security.quarantine.restore',
      moduleId: 'security',
      title: 'Restore quarantined file',
      description: 'Restore one explicitly confirmed file without overwriting an existing destination.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: { quarantineId: { type: 'string' }, destination: { type: 'string' } },
        required: ['quarantineId'],
        additionalProperties: false,
      },
    },
    {
      id: 'security.responses.list',
      moduleId: 'security',
      title: 'List shadow response proposals',
      description: 'Read bounded response proposals; shadow mode never executes system changes.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: { limit: { type: 'number' } },
        additionalProperties: false,
      },
    },
    {
      id: 'security.response.propose',
      moduleId: 'security',
      title: 'Propose a bounded security response',
      description: 'Validate and record a typed response proposal in shadow mode without executing it.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: {
          incidentId: { type: 'string' },
          action: { type: 'string', enum: ['preserve', 'deep_scan', 'isolate', 'block_network', 'suspend_process', 'terminate_process', 'delete'] },
          scope: { type: 'object' },
          rationale: { type: 'array', items: { type: 'string' } },
          proposedBy: { type: 'string', enum: ['rules', 'llm', 'user'] },
          ttlSeconds: { type: 'number' },
        },
        required: ['incidentId', 'action', 'scope'],
        additionalProperties: false,
      },
    },
    {
      id: 'security.response.evaluate',
      moduleId: 'security',
      title: 'Evaluate shadow response proposal',
      description: 'Re-check TTL and gates for a proposal; returns authorized=false and executed=false in shadow mode.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: { proposalId: { type: 'string' } },
        required: ['proposalId'],
        additionalProperties: false,
      },
    },
    {
      id: 'security.response.approve',
      moduleId: 'security',
      title: 'Approve a bounded security response',
      description: 'Send proposal id and Security PIN over a bounded local pipe for revalidation and expiring execution by the elevated service.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: {
          proposalId: { type: 'string' },
          pin: { type: 'string' },
        },
        required: ['proposalId', 'pin'],
        additionalProperties: false,
      },
    },
    {
      id: 'security.response.actions',
      moduleId: 'security',
      title: 'Read response action lifecycle',
      description: 'Read active, rolled-back, and failed privileged response actions.',
      risk: 'read',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    },
    {
      id: 'security.response.service.status',
      moduleId: 'security',
      title: 'Read response executor status',
      description: 'Verify the signed heartbeat of the separate elevated response executor.',
      risk: 'read',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    },
    {
      id: 'security.emergency.status',
      moduleId: 'security',
      title: 'Read emergency response state',
      description: 'Read the signed fail-open emergency state, native-lock result, TTL, and containment status.',
      risk: 'read',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    },
    {
      id: 'security.emergency.resolve',
      moduleId: 'security',
      title: 'Resolve emergency response',
      description: 'After Windows sign-in, verify Security PIN and either release or continue time-bounded containment.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: {
          decision: { type: 'string', enum: ['release', 'continue'] },
          pin: { type: 'string' },
        },
        required: ['decision', 'pin'],
        additionalProperties: false,
      },
    },
    {
      id: 'security.pin.status',
      moduleId: 'security',
      title: 'Read Security PIN status',
      description: 'Read whether the local six-digit Security PIN is configured or rate-limited; never returns the PIN.',
      risk: 'read',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    },
    {
      id: 'security.pin.set',
      moduleId: 'security',
      title: 'Set Security PIN',
      description: 'Set or rotate the local six-digit Security PIN through an ephemeral request file.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: {
          newPin: { type: 'string' },
          confirmation: { type: 'string' },
          currentPin: { type: 'string' },
        },
        required: ['newPin', 'confirmation'],
        additionalProperties: false,
      },
    },
    {
      id: 'security.pin.verify',
      moduleId: 'security',
      title: 'Verify Security PIN',
      description: 'Verify the local Security PIN with rate limiting through an ephemeral request file.',
      risk: 'security-sensitive',
      inputSchema: {
        type: 'object',
        properties: { pin: { type: 'string' } },
        required: ['pin'],
        additionalProperties: false,
      },
    },
    {
      id: 'security.pin.recover',
      moduleId: 'security',
      title: 'Recover Security PIN',
      description: 'Rotate a forgotten Security PIN with a one-time recovery code through an ephemeral request file.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: {
          recoveryCode: { type: 'string' },
          newPin: { type: 'string' },
          confirmation: { type: 'string' },
        },
        required: ['recoveryCode', 'newPin', 'confirmation'],
        additionalProperties: false,
      },
    },
    {
      id: 'security.report.generate',
      moduleId: 'security',
      title: 'Generate security report',
      description: 'Generate a Monarch Security report and persist JSON, Markdown, and HTML artifacts under the local reports directory.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: {
          includeFiles: { type: 'boolean' },
          includeInstalls: { type: 'boolean' },
          fileLimit: { type: 'number' },
          noLlm: { type: 'boolean' },
          summaryOnly: { type: 'boolean' },
          outputDir: { type: 'string' },
        },
        additionalProperties: false,
      },
      routing: {
        aliases: ['security report', 'generate security report', 'отчет безопасности', 'отчёт безопасности'],
        keywords: ['security', 'report', 'summary', 'findings', 'controls', 'безопасность', 'отчет', 'отчёт', 'сводка'],
        examples: ['generate security report', 'сделай отчет безопасности'],
        intentKinds: ['security.report', 'host.report'],
      },
    },
    {
      id: 'security.scan.system',
      moduleId: 'security',
      title: 'Run system security scan',
      description: 'Run a read-only host scan across network, devices, persistence, and security posture.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {
          includeFiles: { type: 'boolean' },
          includeInstalls: { type: 'boolean' },
          fileLimit: { type: 'number' },
          noLlm: { type: 'boolean' },
          summaryOnly: { type: 'boolean' },
        },
        additionalProperties: false,
      },
      routing: {
        aliases: ['security scan', 'scan system security', 'scan-system', 'проверь безопасность', 'скан системы'],
        keywords: ['security', 'scan', 'system', 'network', 'devices', 'persistence', 'posture', 'безопасность', 'скан', 'система', 'сеть'],
        examples: ['run security scan', 'проверь безопасность системы'],
        intentKinds: ['security.scan', 'host.scan'],
      },
    },
    {
      id: 'security.scan.network',
      moduleId: 'security',
      title: 'Scan network security',
      description: 'Run a passive read-only network security scan.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {
          noLlm: { type: 'boolean' },
        },
        additionalProperties: false,
      },
      routing: {
        aliases: ['scan network security', 'security network scan', 'проверь сеть'],
        keywords: ['security', 'network', 'internet', 'connections', 'listeners', 'безопасность', 'сеть', 'соединения'],
        examples: ['scan network security', 'проверь сетевую безопасность'],
        intentKinds: ['security.scan', 'network.scan'],
      },
    },
    {
      id: 'security.network.center',
      moduleId: 'security',
      title: 'Read Network Center',
      description: 'Read live local network profiles, connections, listeners, and integrity-protected history.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: { limit: { type: 'number' } },
        additionalProperties: false,
      },
      routing: {
        aliases: ['network center', 'network activity', 'центр сети', 'сетевая активность'],
        keywords: ['network', 'connections', 'listeners', 'profiles', 'history', 'сеть', 'подключения', 'порты'],
        examples: ['show Network Center', 'покажи сетевую активность'],
        intentKinds: ['security.network.center'],
      },
    },
    {
      id: 'security.network.profile.trust',
      moduleId: 'security',
      title: 'Change trusted network profile',
      description: 'Explicitly trust or untrust one locally fingerprinted network profile.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: {
          profileId: { type: 'string' },
          trusted: { type: 'boolean' },
        },
        required: ['profileId', 'trusted'],
        additionalProperties: false,
      },
      routing: {
        aliases: ['trust network profile', 'доверять сети', 'убрать доверие сети'],
        keywords: ['network', 'profile', 'trust', 'trusted', 'сеть', 'профиль', 'доверие'],
        examples: ['trust this network profile', 'доверять этому профилю сети'],
        intentKinds: ['security.network.profile.trust'],
      },
    },
    {
      id: 'security.scan.devices',
      moduleId: 'security',
      title: 'Scan connected devices',
      description: 'Run a read-only scan of connected devices such as USB, HID, storage, and phones.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {
          noLlm: { type: 'boolean' },
        },
        additionalProperties: false,
      },
      routing: {
        aliases: ['scan security devices', 'scan usb', 'проверь usb', 'проверь устройства'],
        keywords: ['security', 'devices', 'usb', 'hid', 'storage', 'безопасность', 'устройства', 'usb'],
        examples: ['scan connected devices', 'проверь подключенные устройства'],
        intentKinds: ['security.scan', 'device.scan'],
      },
    },
    {
      id: 'security.scan.persistence',
      moduleId: 'security',
      title: 'Scan persistence entries',
      description: 'Run a read-only scan of startup folders, Run keys, and scheduled tasks.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {
          noLlm: { type: 'boolean' },
        },
        additionalProperties: false,
      },
      routing: {
        aliases: ['scan persistence', 'scan autorun', 'проверь автозапуск'],
        keywords: ['security', 'persistence', 'autorun', 'startup', 'scheduled tasks', 'безопасность', 'автозапуск'],
        examples: ['scan persistence entries', 'проверь автозапуск'],
        intentKinds: ['security.scan', 'persistence.scan'],
      },
    },
    {
      id: 'security.scan.posture',
      moduleId: 'security',
      title: 'Scan Defender and firewall posture',
      description: 'Run a read-only scan of Microsoft Defender and firewall posture.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {
          noLlm: { type: 'boolean' },
        },
        additionalProperties: false,
      },
      routing: {
        aliases: ['scan posture', 'check defender', 'check firewall', 'проверь defender', 'проверь firewall'],
        keywords: ['security', 'posture', 'defender', 'firewall', 'безопасность', 'защитник', 'фаервол'],
        examples: ['check Defender posture', 'проверь защитник и firewall'],
        intentKinds: ['security.scan', 'posture.scan'],
      },
    },
    {
      id: 'security.scan.path',
      moduleId: 'security',
      title: 'Scan file or folder path',
      description: 'Run a safe read-only scanner on one file or folder.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {
          path: { type: 'string' },
          recursive: { type: 'boolean' },
          limit: { type: 'number' },
          noLlm: { type: 'boolean' },
        },
        required: ['path'],
        additionalProperties: false,
      },
      routing: {
        aliases: ['scan path', 'scan file', 'scan folder', 'проверь файл', 'проверь папку'],
        keywords: ['security', 'scan', 'file', 'folder', 'path', 'malware', 'безопасность', 'скан', 'файл', 'папка'],
        examples: ['scan file E:\\Downloads\\sample.exe', 'проверь файл E:\\tmp\\sample.exe'],
        intentKinds: ['security.scan', 'file.scan'],
      },
    },
    {
      id: 'security.deep_scan.file',
      moduleId: 'security',
      title: 'Deep scan file',
      description: 'Run deep file inspection with Authenticode facts and optional Defender custom scan.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {
          path: { type: 'string' },
          defender: { type: 'boolean' },
          noLlm: { type: 'boolean' },
        },
        required: ['path'],
        additionalProperties: false,
      },
      routing: {
        aliases: ['deep scan file', 'deep security scan', 'глубокий скан файла'],
        keywords: ['security', 'deep', 'scan', 'authenticode', 'defender', 'безопасность', 'глубокий', 'скан', 'файл'],
        examples: ['deep scan file E:\\Downloads\\sample.exe', 'глубоко проверь файл'],
        intentKinds: ['security.scan', 'file.deep_scan'],
      },
    },
    {
      id: 'security.protection.start',
      moduleId: 'security',
      title: 'Start background protection',
      description: 'Start the Monarch Security background protector.',
      risk: 'execute',
      inputSchema: {
        type: 'object',
        properties: {
          noLlm: { type: 'boolean' },
        },
        additionalProperties: false,
      },
      routing: {
        aliases: ['start security protection', 'start protector', 'включи защиту'],
        keywords: ['security', 'start', 'protection', 'protector', 'enable', 'безопасность', 'защита', 'включи', 'запусти'],
        examples: ['start security protection', 'включи защиту'],
        intentKinds: ['security.protection.start'],
      },
    },
    {
      id: 'security.protection.stop',
      moduleId: 'security',
      title: 'Stop background protection',
      description: 'Stop the Monarch Security background protector using its protected stop-token path.',
      risk: 'execute',
      inputSchema: {
        type: 'object',
        properties: {
          waitSeconds: { type: 'number' },
        },
        additionalProperties: false,
      },
      routing: {
        aliases: ['stop security protection', 'stop protector', 'выключи защиту'],
        keywords: ['security', 'stop', 'protection', 'protector', 'disable', 'безопасность', 'защита', 'выключи', 'останови'],
        examples: ['stop security protection', 'выключи защиту'],
        intentKinds: ['security.protection.stop'],
      },
    },
    {
      id: 'security.baseline.preview',
      moduleId: 'security',
      title: 'Preview persistence baseline changes',
      description: 'Read a bounded persistence diff and digest without changing approved trust state.',
      risk: 'read',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    },
    {
      id: 'security.baseline.write',
      moduleId: 'security',
      title: 'Save security baseline',
      description: 'Write a current security baseline for devices, installs, files, network, persistence, or posture.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: {
          scope: {
            type: 'string',
            enum: ['all', 'devices', 'installs', 'files', 'network', 'persistence', 'posture', 'self-protection'],
          },
          expectedDigest: { type: 'string' },
        },
        additionalProperties: false,
      },
      routing: {
        aliases: ['save security baseline', 'security baseline', 'запомни норму защиты'],
        keywords: ['security', 'baseline', 'normal', 'state', 'безопасность', 'норма', 'baseline'],
        examples: ['save security baseline', 'запомни текущую норму защиты'],
        intentKinds: ['security.baseline'],
      },
    },
    {
      id: 'security.verify.protection',
      moduleId: 'security',
      title: 'Run protection verification lab',
      description: 'Run the inert local verification lab against scanner, rules, and policy.',
      risk: 'execute',
      inputSchema: {
        type: 'object',
        properties: {
          withLlm: { type: 'boolean' },
        },
        additionalProperties: false,
      },
      routing: {
        aliases: ['verify protection', 'security self test', 'самопроверка защиты'],
        keywords: ['security', 'verify', 'protection', 'self-test', 'lab', 'безопасность', 'самопроверка', 'защита'],
        examples: ['verify protection', 'запусти самопроверку защиты'],
        intentKinds: ['security.verify'],
      },
    },
    {
      id: 'security.attack.simulation',
      moduleId: 'security',
      title: 'Run inert attack simulation',
      description: 'Run inert adversarial evasion tests against the detector.',
      risk: 'execute',
      inputSchema: {
        type: 'object',
        properties: {
          withLlm: { type: 'boolean' },
        },
        additionalProperties: false,
      },
      routing: {
        aliases: ['attack simulation', 'security attack simulation', 'симуляция атаки'],
        keywords: ['security', 'attack', 'simulation', 'evasion', 'detector', 'безопасность', 'атака', 'симуляция'],
        examples: ['run attack simulation', 'запусти симуляцию атаки'],
        intentKinds: ['security.attack_simulation'],
      },
    },
    {
      id: 'security.threat.simulation.live',
      moduleId: 'security',
      title: 'Simulate a live Security threat safely',
      description: 'Create a clearly labelled durable critical incident and real notification from inert RAT-like telemetry without executing a payload or applying containment.',
      risk: 'execute',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
      routing: {
        aliases: ['live threat simulation', 'реалистичная имитация угрозы'],
        keywords: ['security', 'threat', 'simulation', 'incident', 'безопасность', 'угроза', 'имитация', 'инцидент'],
        examples: ['simulate a realistic threat safely', 'сымитируй реальную угрозу безопасно'],
        intentKinds: ['security.attack_simulation'],
      },
    },
    {
      id: 'security.benchmark.start',
      moduleId: 'security',
      title: 'Start background protection benchmark',
      description: 'Start a bounded 30-900 second CPU/RSS observation job for the running protector.',
      risk: 'execute',
      inputSchema: {
        type: 'object',
        properties: {
          durationSeconds: { type: 'number' },
          intervalSeconds: { type: 'number' },
        },
        additionalProperties: false,
      },
      routing: {
        aliases: ['security benchmark', 'background protection benchmark', 'бенчмарк защиты'],
        keywords: ['security', 'benchmark', 'cpu', 'rss', 'защита', 'нагрузка', 'ресурсы'],
        examples: ['run five minute security benchmark', 'запусти бенчмарк фоновой защиты'],
        intentKinds: ['security.benchmark.start'],
      },
    },
    {
      id: 'security.benchmark.status',
      moduleId: 'security',
      title: 'Read background benchmark status',
      description: 'Read progress and the final bounded resource observation result.',
      risk: 'read',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    },
    {
      id: 'security.benchmark.cancel',
      moduleId: 'security',
      title: 'Cancel background benchmark',
      description: 'Cancel only the currently owned background benchmark job by exact job id.',
      risk: 'execute',
      inputSchema: {
        type: 'object',
        properties: { jobId: { type: 'string' } },
        required: ['jobId'],
        additionalProperties: false,
      },
    },
    {
      id: 'security.notification.test',
      moduleId: 'security',
      title: 'Send test security notification',
      description: 'Send a synthetic high-risk alert through the notification channel.',
      risk: 'execute',
      inputSchema: {
        type: 'object',
        properties: {},
        additionalProperties: false,
      },
      routing: {
        aliases: ['test security notification', 'test notification', 'тест уведомления защиты'],
        keywords: ['security', 'notification', 'test', 'alert', 'безопасность', 'уведомление', 'тест'],
        examples: ['test security notification', 'проверь уведомление защиты'],
        intentKinds: ['security.notification'],
      },
    },
    {
      id: 'security.controller.check',
      moduleId: 'security',
      title: 'Check capability execution action',
      description: 'Check whether a planned LLM capability execution action is safe and matches the user intent.',
      risk: 'execute',
      inputSchema: {
        type: 'object',
        properties: {
          intentText: { type: 'string' },
          actionModule: { type: 'string' },
          actionCapability: { type: 'string' },
          actionInput: { type: 'string' },
          actionRisk: { type: 'string' },
          requestedBy: { type: 'string' },
          monarchConfirmed: { type: 'boolean' },
          modelProposed: { type: 'boolean' },
          passkey: { type: 'string' },
          noLlm: { type: 'boolean' },
        },
        required: ['intentText', 'actionModule', 'actionCapability', 'actionInput', 'actionRisk', 'requestedBy', 'monarchConfirmed'],
        additionalProperties: false,
      },
    },
    {
      id: 'security.controller.block',
      moduleId: 'security',
      title: 'Permanently block capability execution',
      description: 'Permanently block a capability execution action under Monarch Security.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: {
          capabilityId: { type: 'string' },
        },
        required: ['capabilityId'],
        additionalProperties: false,
      },
    },
  ],
};
