import type { MonarchModuleManifest } from '../../core';

export const coderManifest: MonarchModuleManifest = {
  id: 'coder',
  name: 'Monarch Coder',
  version: '0.1.0',
  kind: 'tooling',
  description: 'Project-scoped autonomous coding tools with durable context and protected host boundaries.',
  owns: ['coder mode', 'coding agent', 'projects', 'code workspace', 'developer tools'],
  permissions: ['read', 'write', 'delete', 'execute', 'network'],
  events: [
    'coder.project.created',
    'coder.project.imported',
    'coder.project.activated',
    'coder.file.written',
    'coder.file.patched',
    'coder.file.deleted',
    'coder.command.completed',
    'coder.skill.validated',
  ],
  capabilities: [
    {
      id: 'coder.projects.list',
      moduleId: 'coder',
      title: 'List Coder projects',
      description: 'List registered coding projects and the active project.',
      risk: 'read',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    },
    {
      id: 'coder.projects.create',
      moduleId: 'coder',
      title: 'Create Coder project',
      description: 'Create a new project under the dedicated Workspace Coder root.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: { name: { type: 'string' } },
        required: ['name'],
        additionalProperties: false,
      },
    },
    {
      id: 'coder.projects.import',
      moduleId: 'coder',
      title: 'Import existing project',
      description: 'Register an existing non-system folder as a Coder project.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: { path: { type: 'string' }, name: { type: 'string' } },
        required: ['path'],
        additionalProperties: false,
      },
    },
    {
      id: 'coder.projects.activate',
      moduleId: 'coder',
      title: 'Activate Coder project',
      description: 'Select the project used by subsequent Coder actions.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: { projectId: { type: 'string' } },
        required: ['projectId'],
        additionalProperties: false,
      },
    },
    {
      id: 'coder.files.list',
      moduleId: 'coder',
      title: 'List project files',
      description: 'List a bounded file tree in the selected project.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {
          projectId: { type: 'string' },
          path: { type: 'string' },
          recursive: { type: 'boolean' },
          limit: { type: 'number' },
        },
        additionalProperties: false,
      },
    },
    {
      id: 'coder.files.read',
      moduleId: 'coder',
      title: 'Read project file',
      description: 'Read a bounded text file from the selected project or another allowed non-system path.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: { projectId: { type: 'string' }, path: { type: 'string' }, maxBytes: { type: 'number' } },
        required: ['path'],
        additionalProperties: false,
      },
    },
    {
      id: 'coder.files.write',
      moduleId: 'coder',
      title: 'Write project file',
      description: 'Atomically create or replace a bounded text file outside protected Monarch and OS paths.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: {
          projectId: { type: 'string' },
          path: { type: 'string' },
          content: { type: 'string' },
          overwrite: { type: 'boolean' },
        },
        required: ['path', 'content'],
        additionalProperties: false,
      },
    },
    {
      id: 'coder.files.patch',
      moduleId: 'coder',
      title: 'Patch project file',
      description: 'Apply exact, atomic text replacements and fail if an edit is ambiguous.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: {
          projectId: { type: 'string' },
          path: { type: 'string' },
          replacements: { type: 'array' },
        },
        required: ['path', 'replacements'],
        additionalProperties: false,
      },
    },
    {
      id: 'coder.files.delete',
      moduleId: 'coder',
      title: 'Delete project file',
      description: 'Delete one file outside protected Monarch and OS paths; recursive directory deletion is unavailable.',
      risk: 'delete',
      inputSchema: {
        type: 'object',
        properties: { projectId: { type: 'string' }, path: { type: 'string' } },
        required: ['path'],
        additionalProperties: false,
      },
    },
    {
      id: 'coder.command.run',
      moduleId: 'coder',
      title: 'Run project command',
      description: 'Run a bounded non-elevated command in the project with dangerous host and Monarch operations blocked.',
      risk: 'execute',
      inputSchema: {
        type: 'object',
        properties: {
          projectId: { type: 'string' },
          executable: { type: 'string' },
          args: { type: 'array' },
          cwd: { type: 'string' },
          timeoutMs: { type: 'number' },
          allowNetwork: { type: 'boolean' },
        },
        required: ['executable'],
        additionalProperties: false,
      },
    },
    {
      id: 'coder.network.fetch',
      moduleId: 'coder',
      title: 'Fetch public web resource',
      description: 'Fetch a bounded public HTTP(S) text resource with DNS and redirect SSRF checks.',
      risk: 'network',
      inputSchema: {
        type: 'object',
        properties: { url: { type: 'string' }, method: { type: 'string' } },
        required: ['url'],
        additionalProperties: false,
      },
    },
    {
      id: 'coder.network.request',
      moduleId: 'coder',
      title: 'Request public web API',
      description: 'Send a bounded HTTP(S) request to a public target with DNS pinning, redirect validation and credential-header blocking.',
      risk: 'network',
      inputSchema: {
        type: 'object',
        properties: {
          url: { type: 'string' },
          method: { type: 'string' },
          headers: { type: 'object' },
          body: { type: 'string' },
        },
        required: ['url'],
        additionalProperties: false,
      },
    },
    {
      id: 'coder.git.status',
      moduleId: 'coder',
      title: 'Inspect Git worktree',
      description: 'Read the active project branch and worktree status.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: { projectId: { type: 'string' } },
        additionalProperties: false,
      },
    },
    {
      id: 'coder.git.diff',
      moduleId: 'coder',
      title: 'Inspect Git diff',
      description: 'Read a bounded project diff without changing Git state.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: { projectId: { type: 'string' }, staged: { type: 'boolean' }, path: { type: 'string' } },
        additionalProperties: false,
      },
    },
    {
      id: 'coder.git.init',
      moduleId: 'coder',
      title: 'Initialize Git repository',
      description: 'Initialize and verify a Git repository inside the active Coder project.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: { projectId: { type: 'string' }, initialBranch: { type: 'string' } },
        additionalProperties: false,
      },
    },
    {
      id: 'coder.git.stage',
      moduleId: 'coder',
      title: 'Stage Git paths',
      description: 'Stage validated project-relative paths and return the observed staged file set.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: { projectId: { type: 'string' }, paths: { type: 'array' } },
        required: ['paths'],
        additionalProperties: false,
      },
    },
    {
      id: 'coder.git.commit',
      moduleId: 'coder',
      title: 'Create verified Git commit',
      description: 'Commit staged project changes with hooks disabled and verify the resulting commit identity.',
      risk: 'execute',
      inputSchema: {
        type: 'object',
        properties: {
          projectId: { type: 'string' },
          message: { type: 'string' },
          authorName: { type: 'string' },
          authorEmail: { type: 'string' },
        },
        required: ['message'],
        additionalProperties: false,
      },
    },
    {
      id: 'coder.git.branch.create',
      moduleId: 'coder',
      title: 'Create Git branch',
      description: 'Create and switch to a validated project branch with hooks disabled, then verify HEAD.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: { projectId: { type: 'string' }, name: { type: 'string' }, startPoint: { type: 'string' } },
        required: ['name'],
        additionalProperties: false,
      },
    },
    {
      id: 'coder.git.push',
      moduleId: 'coder',
      title: 'Push verified Git branch',
      description: 'Push a validated branch to a configured public remote and verify its remote commit.',
      risk: 'network',
      inputSchema: {
        type: 'object',
        properties: {
          projectId: { type: 'string' },
          remote: { type: 'string' },
          branch: { type: 'string' },
          setUpstream: { type: 'boolean' },
        },
        additionalProperties: false,
      },
    },
    {
      id: 'coder.github.status',
      moduleId: 'coder',
      title: 'Inspect GitHub integration',
      description: 'Report GitHub CLI authentication without returning credentials.',
      risk: 'read',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    },
    {
      id: 'coder.github.pr.view',
      moduleId: 'coder',
      title: 'Inspect GitHub pull request',
      description: 'Read structured pull request state for the active project repository.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: { projectId: { type: 'string' }, number: { type: 'number' } },
        required: ['number'],
        additionalProperties: false,
      },
    },
    {
      id: 'coder.github.pr.create',
      moduleId: 'coder',
      title: 'Create verified GitHub pull request',
      description: 'Create a non-interactive GitHub pull request from an already-pushed branch and verify its returned state.',
      risk: 'network',
      inputSchema: {
        type: 'object',
        properties: {
          projectId: { type: 'string' },
          title: { type: 'string' },
          body: { type: 'string' },
          base: { type: 'string' },
          head: { type: 'string' },
          draft: { type: 'boolean' },
        },
        required: ['title', 'body', 'base'],
        additionalProperties: false,
      },
    },
    {
      id: 'coder.huggingface.status',
      moduleId: 'coder',
      title: 'Inspect Hugging Face integration',
      description: 'Report bundled Hugging Face CLI authentication without returning tokens.',
      risk: 'read',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    },
    {
      id: 'coder.huggingface.repo.info',
      moduleId: 'coder',
      title: 'Inspect Hugging Face repository',
      description: 'Read bounded public Hugging Face repository metadata through the Hub API.',
      risk: 'network',
      inputSchema: {
        type: 'object',
        properties: { repoId: { type: 'string' }, repoType: { type: 'string' }, revision: { type: 'string' } },
        required: ['repoId'],
        additionalProperties: false,
      },
    },
    {
      id: 'coder.huggingface.download',
      moduleId: 'coder',
      title: 'Download Hugging Face files',
      description: 'Dry-run, size-check, download and verify selected Hub files into a Coder project without using C: for large data.',
      risk: 'network',
      inputSchema: {
        type: 'object',
        properties: {
          projectId: { type: 'string' },
          repoId: { type: 'string' },
          repoType: { type: 'string' },
          revision: { type: 'string' },
          filenames: { type: 'array' },
          destination: { type: 'string' },
          maxBytes: { type: 'number' },
        },
        required: ['repoId', 'filenames', 'destination'],
        additionalProperties: false,
      },
    },
    {
      id: 'coder.huggingface.upload',
      moduleId: 'coder',
      title: 'Upload project artifact to Hugging Face',
      description: 'Upload a bounded non-sensitive project file or directory and return the verified Hub result.',
      risk: 'network',
      inputSchema: {
        type: 'object',
        properties: {
          projectId: { type: 'string' },
          repoId: { type: 'string' },
          repoType: { type: 'string' },
          localPath: { type: 'string' },
          pathInRepo: { type: 'string' },
          revision: { type: 'string' },
          commitMessage: { type: 'string' },
          createPullRequest: { type: 'boolean' },
        },
        required: ['repoId', 'localPath'],
        additionalProperties: false,
      },
    },
    {
      id: 'coder.skills.create',
      moduleId: 'coder',
      title: 'Create validated project skill',
      description: 'Create a project-local skill through a draft, structural validation, optional command check, and promote-or-delete lifecycle.',
      risk: 'execute',
      inputSchema: {
        type: 'object',
        properties: {
          projectId: { type: 'string' },
          name: { type: 'string' },
          description: { type: 'string' },
          instructions: { type: 'string' },
          validation: { type: 'object' },
        },
        required: ['name', 'description', 'instructions'],
        additionalProperties: false,
      },
    },
    {
      id: 'coder.integrations.status',
      moduleId: 'coder',
      title: 'Inspect coding integrations',
      description: 'Report local Git, GitHub CLI, Hugging Face CLI and network readiness without exposing credentials.',
      risk: 'read',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    },
  ],
};
