import type { MonarchModuleManifest } from '../../core';

export const telegramManifest: MonarchModuleManifest = {
  id: 'telegram',
  name: 'Monarch Telegram',
  version: '0.1.0',
  kind: 'domain',
  description: 'Local Telegram Bot API bridge for trusted Monarch tasks, reminders, polls, rich tables, and notifications.',
  owns: ['telegram', 'bot', 'remote tasks', 'reminders', 'polls', 'notifications'],
  permissions: ['read', 'write', 'network', 'execute'],
  events: [
    'telegram.activated',
    'telegram.started',
    'telegram.stopped',
    'telegram.paired',
    'telegram.pairing.revoked',
    'telegram.remote.paused',
    'telegram.remote.resumed',
    'telegram.update.received',
    'telegram.reminder.sent',
  ],
  capabilities: [
    {
      id: 'telegram.status',
      moduleId: 'telegram',
      title: 'Telegram status',
      description: 'Show local bot configuration, pairing state, polling status, and reminder counts.',
      risk: 'read',
      routing: {
        aliases: ['telegram status', 'bot status', 'статус telegram', 'статус бота'],
        keywords: ['telegram', 'телеграм', 'bot', 'бот', 'status', 'статус', 'pairing', 'привязка'],
        examples: ['покажи статус Telegram-бота'],
        intentKinds: ['integration.read'],
      },
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    },
    {
      id: 'telegram.capabilities.describe',
      moduleId: 'telegram',
      title: 'Describe Telegram bot capabilities',
      description: 'Answer direct questions about what the Telegram bot can do, its plugin directions, and its safety mode.',
      risk: 'read',
      routing: {
        aliases: ['what can the telegram bot do', 'telegram bot capabilities', 'что умеет тг бот', 'что ты умеешь через телеграм'],
        keywords: ['telegram', 'телеграм', 'tg', 'тг', 'bot', 'бот', 'capabilities', 'возможности', 'умеешь', 'можешь', 'plugins', 'плагины', 'security', 'безопасность'],
        examples: ['что ты умеешь через тг бот?', 'какие плагины доступны через Telegram?', 'какая безопасность у тг бота?'],
        intentKinds: ['capabilities_question', 'integration.read'],
      },
      inputSchema: {
        type: 'object',
        properties: { topic: { type: 'string' } },
        additionalProperties: false,
      },
    },
    {
      id: 'telegram.bot.start',
      moduleId: 'telegram',
      title: 'Start Telegram bot',
      description: 'Start the local Telegram long-polling bridge.',
      risk: 'network',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    },
    {
      id: 'telegram.pairing.revoke',
      moduleId: 'telegram',
      title: 'Revoke Telegram pairing',
      description: 'Revoke one paired chat or every Telegram pairing and remove orphaned reminders.',
      risk: 'execute',
      inputSchema: {
        type: 'object',
        properties: { chatId: { type: 'number' } },
        additionalProperties: false,
      },
    },
    {
      id: 'telegram.remote.pause',
      moduleId: 'telegram',
      title: 'Pause Telegram remote tasks',
      description: 'Activate a local kill switch that blocks new pairings, tasks, and mutable Telegram commands.',
      risk: 'execute',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    },
    {
      id: 'telegram.remote.resume',
      moduleId: 'telegram',
      title: 'Resume Telegram remote tasks',
      description: 'Resume Telegram task intake after a local security review.',
      risk: 'execute',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    },
    {
      id: 'telegram.pairing.rotate',
      moduleId: 'telegram',
      title: 'Create Telegram pairing code',
      description: 'Create a fresh short-lived code for pairing a Telegram chat.',
      risk: 'read',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    },
    {
      id: 'telegram.bot.stop',
      moduleId: 'telegram',
      title: 'Stop Telegram bot',
      description: 'Stop local Telegram polling and reminder timers.',
      risk: 'execute',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    },
    {
      id: 'telegram.message.send',
      moduleId: 'telegram',
      title: 'Send Telegram message',
      description: 'Send a message to a paired Telegram chat.',
      risk: 'network',
      inputSchema: {
        type: 'object',
        properties: { chatId: { type: 'number' }, text: { type: 'string' } },
        required: ['text'],
        additionalProperties: false,
      },
    },
    {
      id: 'telegram.poll.send',
      moduleId: 'telegram',
      title: 'Send Telegram poll',
      description: 'Send a native Telegram poll to a paired chat.',
      risk: 'network',
      inputSchema: {
        type: 'object',
        properties: {
          chatId: { type: 'number' },
          question: { type: 'string' },
          options: { type: 'array', items: { type: 'string' } },
          multiple: { type: 'boolean' },
        },
        required: ['question', 'options'],
        additionalProperties: false,
      },
    },
    {
      id: 'telegram.reminder.create',
      moduleId: 'telegram',
      title: 'Create Telegram reminder',
      description: 'Persist a reminder and deliver it to a paired chat at the requested time.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: { chatId: { type: 'number' }, text: { type: 'string' }, dueAt: { type: 'string' } },
        required: ['text', 'dueAt'],
        additionalProperties: false,
      },
    },
    {
      id: 'telegram.reminder.list',
      moduleId: 'telegram',
      title: 'List Telegram reminders',
      description: 'List pending reminders for paired chats.',
      risk: 'read',
      inputSchema: { type: 'object', properties: { chatId: { type: 'number' } }, additionalProperties: false },
    },
    {
      id: 'telegram.reminder.cancel',
      moduleId: 'telegram',
      title: 'Cancel Telegram reminder',
      description: 'Cancel one pending Telegram reminder by id.',
      risk: 'write',
      inputSchema: {
        type: 'object',
        properties: { id: { type: 'string' }, chatId: { type: 'number' } },
        required: ['id'],
        additionalProperties: false,
      },
    },
    {
      id: 'telegram.api.call',
      moduleId: 'telegram',
      title: 'Call Telegram Bot API',
      description: 'Compatibility escape hatch for current Telegram Bot API methods, including rich messages and new media types.',
      risk: 'execute',
      inputSchema: {
        type: 'object',
        properties: { method: { type: 'string' }, parameters: { type: 'object' } },
        required: ['method'],
        additionalProperties: false,
      },
    },
  ],
};
