import type { MonarchModuleManifest } from '../../core';

const OSCAR_MODEL_IDS = [
  'weak',
  'medium',
  'powerful',
  'reasoning',
  'gemma',
  'gemma_low',
  'gemma_high',
  'gemma4-fast',
  'gemma4-balanced',
  'gemma4-deepthinking',
  'gemma4-31b',
  'qwen3-coder-30b-a3b-instruct',
  'deepseek-coder-v2-lite-instruct',
];

const OSCAR_CHAT_INPUT_PROPERTIES = {
  messages: { type: 'array' },
  conversation_id: { type: 'string' },
  incognito: { type: 'boolean' },
  image_attachments: { type: 'array' },
  research_mode: { type: 'string', enum: ['auto', 'off', 'deep'] },
  use_memory: { type: 'boolean' },
  reasoning_effort: { type: 'string' },
  requested_model: { type: 'string', enum: OSCAR_MODEL_IDS },
  model_selection_source: { type: 'string', enum: ['auto', 'user-explicit', 'fallback', 'recovery'] },
  deep_thinking_consent: { type: 'string', enum: ['allow', 'deny'] },
  route: { type: 'object' },
  max_new_tokens: { type: 'number' },
  temperature: { type: 'number' },
  top_p: { type: 'number' },
};

function createOscarChatInputSchema({ webSearch = false } = {}) {
  return {
    type: 'object',
    properties: {
      ...OSCAR_CHAT_INPUT_PROPERTIES,
      ...(webSearch ? { web_search: { type: 'boolean' } } : {}),
    },
    required: ['messages'],
    additionalProperties: false,
  };
}

export const oscarManifest: MonarchModuleManifest = {
  id: 'oscar',
  name: 'Monarch Oscar',
  version: '0.1.0',
  kind: 'domain',
  description: 'Monarch-native compatibility surface for porting the Oscar local agent into Monarch.',
  owns: [
    'oscar',
    'chat',
    'local agent',
    'web search',
    'oscar memory',
    'оскар',
    'чат',
    'локальный агент',
    'поиск',
    'память oscar',
  ],
  permissions: ['none', 'read', 'network', 'execute'],
  events: [
    'oscar.activated',
    'oscar.backend.checked',
    'oscar.backend.started',
    'oscar.backend.stopped',
    'oscar.generation.cancelled',
    'oscar.model.unloaded',
    'oscar.chat.completed',
    'oscar.voice.fast.completed',
    'oscar.voice.realtime.completed',
    'oscar.conversations.changed',
    'oscar.memory.changed',
    'oscar.search.completed',
  ],
  capabilities: [
    {
      id: 'oscar.status',
      moduleId: 'oscar',
      title: 'Read Oscar status',
      description: 'Read the configured Oscar project path, bridge endpoint, backend health, model status, and memory stats.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {},
        additionalProperties: false,
      },
      routing: {
        aliases: ['oscar status', 'oscar health', 'статус oscar', 'статус оскар'],
        keywords: ['oscar', 'status', 'health', 'model', 'memory', 'оскар', 'статус', 'здоровье', 'модель', 'память'],
        examples: ['show Oscar status', 'покажи статус Oscar'],
        intentKinds: ['oscar.read', 'oscar.status'],
      },
    },
    {
      id: 'oscar.backend.start',
      moduleId: 'oscar',
      title: 'Start Oscar backend',
      description: 'Start the managed local Oscar backend and verify health, model status, and memory stats.',
      risk: 'execute',
      inputSchema: {
        type: 'object',
        properties: {},
        additionalProperties: false,
      },
      routing: {
        aliases: ['start oscar backend', 'start oscar runtime', 'запусти backend oscar', 'запусти оскар'],
        keywords: ['oscar', 'backend', 'runtime', 'start', 'launch', 'оскар', 'запусти', 'включи'],
        examples: ['start Oscar backend', 'запусти backend Oscar'],
        intentKinds: ['oscar.backend.start', 'runtime.start'],
      },
    },
    {
      id: 'oscar.model.unload',
      moduleId: 'oscar',
      title: 'Unload Oscar model',
      description: 'Release loaded Oscar model weights and CUDA/CPU memory from the local backend.',
      risk: 'execute',
      inputSchema: {
        type: 'object',
        properties: {},
        additionalProperties: false,
      },
      routing: {
        aliases: ['oscar unload', 'unload oscar model', 'stop oscar model', 'free oscar memory'],
        keywords: ['oscar', 'unload', 'free', 'memory', 'model', 'stop'],
        examples: ['unload Oscar model', 'free Oscar memory'],
        intentKinds: ['oscar.model.unload', 'runtime.stop'],
      },
    },
    {
      id: 'oscar.generation.cancel',
      moduleId: 'oscar',
      title: 'Cancel Oscar generation',
      description: 'Cancel the currently running Oscar model generation without stopping the backend.',
      risk: 'none',
      inputSchema: {
        type: 'object',
        properties: {},
        additionalProperties: false,
      },
      routing: {
        aliases: ['cancel oscar generation', 'abort oscar response', 'отмени генерацию oscar', 'сбрось очередь oscar'],
        keywords: ['oscar', 'cancel', 'abort', 'generation', 'queue', 'оскар', 'отмени', 'прерви', 'очередь'],
        examples: ['cancel Oscar generation', 'отмени генерацию Oscar'],
        intentKinds: ['oscar.generation.cancel', 'runtime.cancel'],
      },
    },
    {
      id: 'oscar.backend.stop',
      moduleId: 'oscar',
      title: 'Stop Oscar backend',
      description: 'Stop the local Oscar backend process tree to release Python, CUDA, and model memory completely.',
      risk: 'execute',
      inputSchema: {
        type: 'object',
        properties: {},
        additionalProperties: false,
      },
      routing: {
        aliases: ['stop oscar backend', 'stop oscar runtime', 'kill oscar process'],
        keywords: ['oscar', 'backend', 'runtime', 'process', 'stop', 'kill'],
        examples: ['stop Oscar backend', 'free all Oscar process memory'],
        intentKinds: ['oscar.backend.stop', 'runtime.stop'],
      },
    },
    {
      id: 'oscar.chat.local',
      moduleId: 'oscar',
      title: 'Run Oscar local chat',
      description: 'Send a chat request to Oscar-compatible local chat without enabling web search.',
      risk: 'read',
      inputSchema: createOscarChatInputSchema(),
      routing: {
        aliases: ['ask oscar', 'oscar chat', 'спроси oscar', 'спроси оскар', 'чат oscar'],
        keywords: ['oscar', 'chat', 'ask', 'answer', 'assistant', 'gemma', 'оскар', 'чат', 'спроси', 'ответ', 'гемма'],
        examples: ['ask Oscar to summarize this', 'спроси Oscar без веб поиска', 'ask Oscar in Gemma Mode'],
        intentKinds: ['oscar.chat', 'chat.local'],
      },
    },
    {
      id: 'oscar.chat.route',
      moduleId: 'oscar',
      title: 'Preview Oscar chat route',
      description: 'Preview automatic model and web-search routing without starting generation.',
      risk: 'read',
      inputSchema: createOscarChatInputSchema(),
    },
    {
      id: 'oscar.voice.fast',
      moduleId: 'oscar',
      title: 'Run the isolated Fast voice lane',
      description: 'Generate one bounded spoken response through the dedicated Fast voice endpoint with ephemeral Voice-session context but without standard chat memory, tools, search, or prompt assembly.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {
          text: { type: 'string', minLength: 1, maxLength: 1200 },
          language: { type: 'string', enum: ['ru', 'uk', 'bg', 'en'] },
          history: {
            type: 'array',
            maxItems: 8,
            items: {
              type: 'object',
              properties: {
                role: { type: 'string', enum: ['user', 'assistant'] },
                content: { type: 'string', minLength: 1, maxLength: 800 },
              },
              required: ['role', 'content'],
              additionalProperties: false,
            },
          },
        },
        required: ['text'],
        additionalProperties: false,
      },
      routing: {
        aliases: ['fast voice response', 'сложный голосовой ответ'],
        keywords: ['voice', 'fast', 'spoken', 'голос', 'сложный'],
        examples: ['answer this complex voice turn through Fast'],
        intentKinds: ['voice.read'],
      },
    },
    {
      id: 'oscar.voice.realtime',
      moduleId: 'oscar',
      title: 'Run isolated realtime voice search',
      description: 'Search public web excerpts through the safe bounded voice path and generate one short spoken answer with ephemeral Voice-session context.',
      risk: 'network',
      inputSchema: {
        type: 'object',
        properties: {
          text: { type: 'string', minLength: 1, maxLength: 600 },
          kind: { type: 'string', enum: ['weather', 'web-search'] },
          language: { type: 'string', enum: ['ru', 'uk', 'bg', 'en'] },
          location: { type: 'string', minLength: 1, maxLength: 120 },
          history: {
            type: 'array',
            maxItems: 8,
            items: {
              type: 'object',
              properties: {
                role: { type: 'string', enum: ['user', 'assistant'] },
                content: { type: 'string', minLength: 1, maxLength: 800 },
              },
              required: ['role', 'content'],
              additionalProperties: false,
            },
          },
        },
        required: ['text', 'kind'],
        additionalProperties: false,
      },
      routing: {
        aliases: ['realtime voice search', 'актуальный голосовой поиск'],
        keywords: ['voice', 'realtime', 'weather', 'search', 'погода', 'поиск'],
        examples: ['tell me the current weather through voice search'],
        intentKinds: ['web.search'],
      },
    },
    {
      id: 'oscar.chat.stream',
      moduleId: 'oscar',
      title: 'Run Oscar chat stream',
      description: 'Send a chat request to Oscar-compatible local chat and stream the response.',
      risk: 'read',
      inputSchema: createOscarChatInputSchema({ webSearch: true }),
      routing: {
        aliases: ['stream oscar chat'],
        keywords: ['oscar', 'stream', 'chat', 'gemma'],
        intentKinds: ['oscar.chat.stream'],
      },
    },
    {
      id: 'oscar.chat.web',
      moduleId: 'oscar',
      title: 'Run Oscar chat with web search',
      description: 'Send a chat request to Oscar-compatible local chat with web search enabled.',
      risk: 'network',
      inputSchema: createOscarChatInputSchema(),
      routing: {
        aliases: ['ask oscar with web', 'oscar web chat', 'спроси oscar с вебом', 'oscar web search'],
        keywords: ['oscar', 'chat', 'web', 'search', 'internet', 'оскар', 'чат', 'веб', 'поиск', 'интернет'],
        examples: ['ask Oscar with web search', 'спроси Oscar с веб поиском'],
        intentKinds: ['oscar.chat', 'web.search'],
      },
    },
    {
      id: 'oscar.conversations.manage',
      moduleId: 'oscar',
      title: 'Manage Oscar conversations',
      description: 'List, create, open, append messages, rename, archive, or delete persistent Oscar conversations.',
      risk: 'none',
      inputSchema: {
        type: 'object',
        properties: {
          action: { type: 'string', enum: ['list', 'create', 'get', 'update', 'edit_message', 'append_message', 'delete'] },
          id: { type: 'string' },
          message_id: { type: 'string' },
          content: { type: 'string' },
          role: { type: 'string', enum: ['user', 'assistant'] },
          token_count: { type: 'number' },
          elapsed_ms: { type: 'number' },
          model_tier: { type: 'string' },
          message_limit: { type: 'number', minimum: 1, maximum: 200 },
          before: { type: 'number', minimum: 1 },
          title: { type: 'string' },
          archived: { type: 'boolean' },
        },
        required: ['action'],
        additionalProperties: false,
      },
      routing: {
        aliases: ['chat history', 'conversation history', 'история чатов'],
        keywords: ['oscar', 'history', 'conversation', 'chat', 'история', 'чат', 'диалог'],
        examples: ['show Oscar chat history', 'покажи историю чатов Oscar'],
        intentKinds: ['oscar.history', 'conversation.manage'],
      },
    },
    {
      id: 'oscar.memory.manage',
      moduleId: 'oscar',
      title: 'Manage Oscar memories',
      description: 'List, add, edit, enable, disable, or delete explicit long-term Oscar memories.',
      risk: 'none',
      inputSchema: {
        type: 'object',
        properties: {
          action: { type: 'string', enum: ['list', 'create', 'update', 'delete'] },
          id: { type: 'string' },
          content: { type: 'string' },
          category: { type: 'string' },
          type: { type: 'string' },
          title: { type: 'string' },
          tags: { type: 'array', items: { type: 'string' } },
          priority: { type: 'number' },
          expires_at: { type: 'string' },
          related_files: { type: 'array', items: { type: 'string' } },
          related_modules: { type: 'array', items: { type: 'string' } },
          closed: { type: 'boolean' },
          enabled: { type: 'boolean' },
        },
        required: ['action'],
        additionalProperties: false,
      },
      routing: {
        aliases: ['manage oscar memory', 'memory settings', 'управление памятью'],
        keywords: ['oscar', 'memory', 'remember', 'forget', 'память', 'запомни', 'забудь'],
        examples: ['manage Oscar memories', 'открой управление памятью Oscar'],
        intentKinds: ['oscar.memory', 'memory.manage'],
      },
    },
    {
      id: 'oscar.memory.search',
      moduleId: 'oscar',
      title: 'Search Oscar memory',
      description: 'Search the existing Oscar SQLite memory through its local backend.',
      risk: 'read',
      inputSchema: {
        type: 'object',
        properties: {
          query: { type: 'string' },
          limit: { type: 'number' },
        },
        required: ['query'],
        additionalProperties: false,
      },
      routing: {
        aliases: ['search oscar memory', 'oscar memory', 'найди в памяти oscar', 'память оскар'],
        keywords: ['oscar', 'memory', 'search', 'recall', 'оскар', 'память', 'найди', 'вспомни'],
        examples: ['search Oscar memory for Monarch', 'найди в памяти Oscar Monarch'],
        intentKinds: ['oscar.memory', 'memory.search'],
      },
    },
    {
      id: 'oscar.search.ingest',
      moduleId: 'oscar',
      title: 'Run Oscar web search ingest',
      description: 'Run Oscar web search and ingest fetched pages into Oscar memory through its local backend.',
      risk: 'network',
      inputSchema: {
        type: 'object',
        properties: {
          query: { type: 'string' },
          max_results: { type: 'number' },
          fetch_pages: { type: 'boolean' },
        },
        required: ['query'],
        additionalProperties: false,
      },
      routing: {
        aliases: ['oscar search', 'oscar web ingest', 'поиск oscar', 'веб поиск оскар'],
        keywords: ['oscar', 'web', 'search', 'ingest', 'internet', 'оскар', 'веб', 'поиск', 'индексация'],
        examples: ['Oscar search latest local AI news', 'запусти поиск Oscar'],
        intentKinds: ['oscar.search', 'web.search'],
      },
    },
  ],
};
